#ifndef GUARD_CONSTANTS_DIFFICULTY_H
#define GUARD_CONSTANTS_DIFFICULTY_H

enum DifficultySetting
{
    DIFFICULTY_NORMAL,
    DIFFICULTY_HARD,
    DIFFICULTY_NIGHTMARE,
    NUM_DIFFICULTY_SETTINGS
};

#endif // GUARD_CONSTANTS_DIFFICULTY_H
