#ifndef GUARD_CONSTANTS_PERSONALITY_TEST_H
#define GUARD_CONSTANTS_PERSONALITY_TEST_H

#include "constants/monster.h"

enum NaturePersonalities
{
    HARDY,
    DOCILE,
    BRAVE,
    JOLLY,
    IMPISH,
    NAIVE,
    TIMID,
    HASTY,
    SASSY,
    CALM,
    RELAXED,
    LONELY,
    QUIRKY,
    MISC,
};

// NUM_PARTNERS defined in monster.h
#define NUM_QUIZ_QUESTIONS 55
#define MAX_ASKED_QUESTIONS 8
#define NUM_PERSONALITIES MISC
#define NUM_PERSONALITY_TEST_EFFECTS (NUM_PERSONALITIES + 3)

#define BRAVE_2B_TRIGGER 99

#endif // GUARD_CONSTANTS_PERSONALITY_TEST_H
