#!/usr/bin/env python3
"""
Generate the type weather table from docs/weather.csv.
"""

from __future__ import annotations

import argparse
import csv
import pathlib
import sys
from typing import Dict, List

TYPE_ORDER = [
    "NONE",
    "NORMAL",
    "FIRE",
    "WATER",
    "GRASS",
    "ELECTRIC",
    "ICE",
    "FIGHTING",
    "POISON",
    "GROUND",
    "FLYING",
    "PSYCHIC",
    "BUG",
    "ROCK",
    "GHOST",
    "DRAGON",
    "DARK",
    "STEEL",
]

TYPE_MAP: Dict[str, str] = {
    "NONE": "TYPE_NONE",
    "NORMAL": "TYPE_NORMAL",
    "FIRE": "TYPE_FIRE",
    "WATER": "TYPE_WATER",
    "GRASS": "TYPE_GRASS",
    "ELECTRIC": "TYPE_ELECTRIC",
    "ICE": "TYPE_ICE",
    "FIGHTING": "TYPE_FIGHTING",
    "POISON": "TYPE_POISON",
    "GROUND": "TYPE_GROUND",
    "FLYING": "TYPE_FLYING",
    "PSYCHIC": "TYPE_PSYCHIC",
    "BUG": "TYPE_BUG",
    "ROCK": "TYPE_ROCK",
    "GHOST": "TYPE_GHOST",
    "DRAGON": "TYPE_DRAGON",
    "DARK": "TYPE_DARK",
    "STEEL": "TYPE_STEEL",
}

WEATHER_MAP: Dict[str, str] = {
    "CLEAR": "WEATHER_CLEAR",
    "SUNNY": "WEATHER_SUNNY",
    "SANDSTORM": "WEATHER_SANDSTORM",
    "CLOUDY": "WEATHER_CLOUDY",
    "RAIN": "WEATHER_RAIN",
    "HAIL": "WEATHER_HAIL",
    "FOG": "WEATHER_FOG",
    "SNOW": "WEATHER_SNOW",
}

MAX_WEATHERS_PER_TYPE = 8


def normalize_key(value: str) -> str:
    return value.strip().upper().replace("-", "_").replace(" ", "_")


def parse_weather_list(raw: str, type_name: str) -> List[str]:
    weathers: List[str] = []
    for token in raw.replace(",", " ").split():
        key = normalize_key(token)
        if not key:
            continue
        if key not in WEATHER_MAP:
            raise SystemExit(f"Unknown weather '{token}' for type {type_name}")
        mapped = WEATHER_MAP[key]
        if mapped not in weathers:
            weathers.append(mapped)
    if len(weathers) > MAX_WEATHERS_PER_TYPE:
        raise SystemExit(
            f"Too many weather entries for type {type_name}: "
            f"{len(weathers)} > {MAX_WEATHERS_PER_TYPE}"
        )
    return weathers


def read_csv(path: pathlib.Path) -> Dict[str, List[str]]:
    pools: Dict[str, List[str]] = {name: [] for name in TYPE_ORDER}
    seen_types = set()
    with path.open(newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        for row in reader:
            raw_type = (row.get("Type") or row.get("type") or "").strip()
            if not raw_type:
                raise SystemExit(f"Missing Type value in row: {row!r}")
            type_name = normalize_key(raw_type)
            if type_name not in TYPE_MAP:
                raise SystemExit(f"Unknown type '{raw_type}' in {path}")
            if type_name in seen_types:
                raise SystemExit(f"Duplicate row for type '{type_name}' in {path}")
            seen_types.add(type_name)

            raw_weather = (row.get("Weather") or row.get("weather") or "").strip()
            if not raw_weather:
                continue
            pools[type_name] = parse_weather_list(raw_weather, type_name)
    return pools


def write_c_file(path: pathlib.Path, pools: Dict[str, List[str]]) -> None:
    with path.open("w", encoding="utf-8") as handle:
        handle.write("// Auto-generated by scripts/build_type_weather_table.py — do not edit.\n")
        handle.write('#include "global.h"\n')
        handle.write('#include "type_selection.h"\n')
        handle.write('#include "constants/type.h"\n')
        handle.write('#include "constants/weather.h"\n\n')
        handle.write("// Generated from docs/weather.csv.\n")
        handle.write("const TypeWeatherPool gTypeWeatherTable[NUM_TYPES] = {\n")

        for type_name in TYPE_ORDER:
            type_const = TYPE_MAP[type_name]
            weather_values = pools.get(type_name, [])
            padded = weather_values + ["WEATHER_CLEAR"] * (MAX_WEATHERS_PER_TYPE - len(weather_values))
            handle.write(f"    [{type_const}] = {{\n")
            handle.write(f"        .weathers = {{{', '.join(padded)}}},\n")
            handle.write(f"        .count = {len(weather_values)},\n")
            handle.write("    },\n")

        handle.write("};\n")


def main(argv: List[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("csv", type=pathlib.Path, help="Path to docs/weather.csv")
    parser.add_argument("out", type=pathlib.Path, help="Output C file path")
    args = parser.parse_args(argv)

    pools = read_csv(args.csv)
    write_c_file(args.out, pools)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
