#!/usr/bin/env python3
"""
Generate roguelike item pools from rogue_files/items.csv.
"""

from __future__ import annotations

import argparse
import csv
import pathlib
import sys
from typing import Dict, List


POOL_FIELDS = {
    "PrimaryLootDrop": "primary_loot",
    "SecondaryLootDrop": "secondary_loot",
    "KecleonShopRareItem": "kecleon_rare",
    "KecleonShopCommonItem": "kecleon_common",
    "NormalItemDrop": "normal",
    "RareItemDrop": "rare",
    "MonsterHouseDrop": "monster_house",
}

# Ordered to match RogueItemPoolId.
POOL_ORDER = [
    ("primary_loot", "ROGUE_ITEM_POOL_PRIMARY_LOOT", "sRoguePrimaryLootItems", "Primary loot"),
    ("secondary_loot", "ROGUE_ITEM_POOL_SECONDARY_LOOT", "sRogueSecondaryLootItems", "Secondary loot"),
    ("kecleon_rare", "ROGUE_ITEM_POOL_KECLEON_RARE", "sRogueKecleonRareItems", "Kecleon rare"),
    ("kecleon_common", "ROGUE_ITEM_POOL_KECLEON_COMMON", "sRogueKecleonCommonItems", "Kecleon common"),
    ("normal", "ROGUE_ITEM_POOL_NORMAL", "sRogueNormalItems", "Normal items"),
    ("rare", "ROGUE_ITEM_POOL_RARE", "sRogueRareItems", "Rare items"),
    ("monster_house", "ROGUE_ITEM_POOL_MONSTER_HOUSE", "sRogueMonsterHouseItems", "Monster House"),
]

ITEM_POKE_ID = 105  # ITEM_POKE
# Give money heavy weight in normal + shop pools so it shows up regularly.
# These are extra copies of ITEM_POKE appended to each pool.
MONEY_BONUS_NORMAL = 20
MONEY_BONUS_SHOP = 10
EXTRA_POOL_ITEMS = {
    "normal": [ITEM_POKE_ID] * MONEY_BONUS_NORMAL,
    "monster_house": [ITEM_POKE_ID],
    "kecleon_common": [ITEM_POKE_ID] * MONEY_BONUS_SHOP,
}


def parse_bool(value: str, field: str, row_num: int) -> bool:
    text = (value or "").strip().upper()
    if text in {"TRUE", "T", "1", "YES", "Y"}:
        return True
    if text in {"FALSE", "F", "0", "NO", "N", ""}:
        return False
    raise SystemExit(f"Unrecognized boolean '{value}' for {field} on row {row_num}")


def read_csv(path: pathlib.Path) -> Dict[str, List[int]]:
    pools: Dict[str, List[int]] = {key: [] for key in POOL_FIELDS.values()}
    seen: Dict[str, set[int]] = {key: set() for key in POOL_FIELDS.values()}

    with path.open(newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        missing = set(POOL_FIELDS) - set(reader.fieldnames or [])
        if missing:
            raise SystemExit(f"{path} missing expected columns: {', '.join(sorted(missing))}")

        for row_num, row in enumerate(reader, start=2):
            id_raw = (row.get("ID") or "").strip()
            if not id_raw:
                raise SystemExit(f"Missing ID on row {row_num} in {path}")
            try:
                item_id = int(id_raw, 10)
            except ValueError as exc:
                raise SystemExit(f"Invalid ID '{id_raw}' on row {row_num} in {path}") from exc
            if item_id <= 0:
                raise SystemExit(f"ID must be positive on row {row_num} in {path}")

            for column, pool_key in POOL_FIELDS.items():
                flag = parse_bool(row.get(column, ""), column, row_num)
                if flag:
                    if item_id in seen[pool_key]:
                        raise SystemExit(f"Duplicate ID {item_id} for {column} on row {row_num} in {path}")
                    seen[pool_key].add(item_id)
                    pools[pool_key].append(item_id)

    for pool_key, extras in EXTRA_POOL_ITEMS.items():
        for item_id in extras:
            if item_id not in seen[pool_key]:
                seen[pool_key].add(item_id)
                pools[pool_key].append(item_id)

    return pools


def write_c_file(path: pathlib.Path, pools: Dict[str, List[int]]) -> None:
    with path.open("w", encoding="utf-8") as handle:
        handle.write("// Auto-generated by scripts/build_rogue_item_tables.py — do not edit.\n")
        handle.write('#include "global.h"\n')
        handle.write('#include "rogue_item_tables.h"\n')
        handle.write('#include "constants/item.h"\n\n')

        for pool_key, _, array_name, _ in POOL_ORDER:
            items = pools.get(pool_key, [])
            if not items:
                continue
            handle.write(f"static const u16 {array_name}[] = {{\n")
            for item_id in items:
                handle.write(f"    {item_id},\n")
            handle.write("};\n\n")

        handle.write("const RogueItemPool gRogueItemPools[ROGUE_ITEM_POOL_COUNT] = {\n")
        for pool_key, enum_name, array_name, _ in POOL_ORDER:
            items = pools.get(pool_key, [])
            pointer = array_name if items else "NULL"
            count = len(items)
            handle.write(f"    [{enum_name}] = {{ {pointer}, {count} }},\n")
        handle.write("};\n\n")

        handle.write("const char *const gRogueItemPoolNames[ROGUE_ITEM_POOL_COUNT] = {\n")
        for _, enum_name, _, label in POOL_ORDER:
            handle.write(f"    [{enum_name}] = \"{label}\",\n")
        handle.write("};\n")


def main(argv: List[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("csv", type=pathlib.Path, help="Path to rogue_files/items.csv")
    parser.add_argument("out", type=pathlib.Path, help="Output C file path")
    args = parser.parse_args(argv)

    pools = read_csv(args.csv)
    write_c_file(args.out, pools)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
