#!/usr/bin/env python3
"""
Generate the type boss table from docs/type_bosses.csv.
"""

from __future__ import annotations

import argparse
import csv
import pathlib
import sys
from typing import Dict, List

MAX_BOSSES_PER_TYPE = 2

TYPE_NAMES = [
    "NONE",
    "NORMAL",
    "FIRE",
    "WATER",
    "GRASS",
    "ELECTRIC",
    "ICE",
    "FIGHTING",
    "POISON",
    "GROUND",
    "FLYING",
    "PSYCHIC",
    "BUG",
    "ROCK",
    "GHOST",
    "DRAGON",
    "DARK",
    "STEEL",
]

TYPE_MAP: Dict[str, str] = {
    "NONE": "TYPE_NONE",
    "NORMAL": "TYPE_NORMAL",
    "FIRE": "TYPE_FIRE",
    "WATER": "TYPE_WATER",
    "GRASS": "TYPE_GRASS",
    "ELECTRIC": "TYPE_ELECTRIC",
    "ICE": "TYPE_ICE",
    "FIGHTING": "TYPE_FIGHTING",
    "POISON": "TYPE_POISON",
    "GROUND": "TYPE_GROUND",
    "FLYING": "TYPE_FLYING",
    "PSYCHIC": "TYPE_PSYCHIC",
    "BUG": "TYPE_BUG",
    "ROCK": "TYPE_ROCK",
    "GHOST": "TYPE_GHOST",
    "DRAGON": "TYPE_DRAGON",
    "DARK": "TYPE_DARK",
    "STEEL": "TYPE_STEEL",
}

SPECIES_MAP: Dict[str, str] = {
    "HERACROSS": "MONSTER_HERACROSS",
    "PINSIR": "MONSTER_PINSIR",
    "ABSOL": "MONSTER_ABSOL",
    "SHIFTRY": "MONSTER_SHIFTRY",
    "LATIAS": "MONSTER_LATIAS",
    "LATIOS": "MONSTER_LATIOS",
    "ZAPDOS": "MONSTER_ZAPDOS",
    "RAIKOU": "MONSTER_RAIKOU",
    "MACHAMP": "MONSTER_MACHAMP",
    "MEDICHAM": "MONSTER_MEDICHAM",
    "MOLTRES": "MONSTER_MOLTRES",
    "ENTEI": "MONSTER_ENTEI",
    "HO_OH": "MONSTER_HO_OH",
    "RAYQUAZA": "MONSTER_RAYQUAZA",
    "GENGAR": "MONSTER_GENGAR",
    "DUSCLOPS": "MONSTER_DUSCLOPS",
    "CELEBI": "MONSTER_CELEBI",
    "VENUSAUR": "MONSTER_VENUSAUR",
    "GROUDON": "MONSTER_GROUDON",
    "CLAYDOL": "MONSTER_CLAYDOL",
    "ARTICUNO": "MONSTER_ARTICUNO",
    "REGICE": "MONSTER_REGICE",
    "MEWTWO": "MONSTER_MEWTWO",
    "MEW": "MONSTER_MEW",
    "MUK": "MONSTER_MUK",
    "CROBAT": "MONSTER_CROBAT",
    "LUGIA": "MONSTER_LUGIA",
    "DEOXYS": "MONSTER_DEOXYS_NORMAL",
    "REGIROCK": "MONSTER_REGIROCK",
    "TYRANITAR": "MONSTER_TYRANITAR",
    "REGISTEEL": "MONSTER_REGISTEEL",
    "JIRACHI": "MONSTER_JIRACHI",
    "SUICUNE": "MONSTER_SUICUNE",
    "KYOGRE": "MONSTER_KYOGRE",
}


def normalize_key(value: str) -> str:
    return value.strip().upper().replace("-", "_").replace(" ", "_")


def parse_csv(path: pathlib.Path) -> Dict[str, List[str]]:
    pools: Dict[str, List[str]] = {name: [] for name in TYPE_NAMES}

    with path.open(newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        for row in reader:
            name = normalize_key(row.get("Pokemon", ""))
            type_name = normalize_key(row.get("Type", ""))

            if not name or not type_name:
                raise SystemExit(f"Invalid row in {path}: {row!r}")
            if type_name not in TYPE_MAP:
                raise SystemExit(f"Unknown type '{type_name}' in {path}")
            if name not in SPECIES_MAP:
                raise SystemExit(f"Unknown species '{name}' in {path}")
            if len(pools[type_name]) >= MAX_BOSSES_PER_TYPE:
                raise SystemExit(f"Too many bosses for type {type_name} (max {MAX_BOSSES_PER_TYPE})")

            pools[type_name].append(SPECIES_MAP[name])

    for type_name in TYPE_NAMES:
        if type_name == "NONE":
            continue
        count = len(pools[type_name])
        if count != MAX_BOSSES_PER_TYPE:
            raise SystemExit(
                f"Type {type_name} has {count} bosses; expected {MAX_BOSSES_PER_TYPE}. "
                f"Check docs/type_bosses.csv."
            )

    return pools


def write_c_file(path: pathlib.Path, pools: Dict[str, List[str]]) -> None:
    with path.open("w", encoding="utf-8") as handle:
        handle.write("// Auto-generated by scripts/build_type_boss_table.py — do not edit.\n")
        handle.write('#include "global.h"\n')
        handle.write('#include "type_selection.h"\n')
        handle.write('#include "constants/monster.h"\n')
        handle.write('#include "constants/type.h"\n\n')
        handle.write("const TypeBossPool gTypeBossTable[NUM_TYPES] = {\n")

        for type_name in TYPE_NAMES:
            type_const = TYPE_MAP[type_name]
            species = list(pools.get(type_name, []))
            count = len(species)
            while len(species) < MAX_BOSSES_PER_TYPE:
                species.append("MONSTER_NONE")

            handle.write(f"    [{type_const}] = {{\n")
            handle.write(f"        .species = {{{', '.join(species)}}},\n")
            handle.write(f"        .count = {count},\n")
            handle.write("    },\n")

        handle.write("};\n")


def main(argv: List[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("csv", type=pathlib.Path, help="Path to docs/type_bosses.csv")
    parser.add_argument("out", type=pathlib.Path, help="Output C file path")
    args = parser.parse_args(argv)

    pools = parse_csv(args.csv)
    write_c_file(args.out, pools)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
