#!/usr/bin/env python3
"""
Generate the seed hint table from docs/type_choices.csv.
"""

from __future__ import annotations

import argparse
import csv
import pathlib
import sys
from typing import Dict, List, Tuple


TYPE_MAP: Dict[str, str] = {
    "NONE": "TYPE_NONE",
    "NORMAL": "TYPE_NORMAL",
    "FIRE": "TYPE_FIRE",
    "WATER": "TYPE_WATER",
    "GRASS": "TYPE_GRASS",
    "ELECTRIC": "TYPE_ELECTRIC",
    "ICE": "TYPE_ICE",
    "FIGHTING": "TYPE_FIGHTING",
    "POISON": "TYPE_POISON",
    "GROUND": "TYPE_GROUND",
    "FLYING": "TYPE_FLYING",
    "PSYCHIC": "TYPE_PSYCHIC",
    "BUG": "TYPE_BUG",
    "ROCK": "TYPE_ROCK",
    "GHOST": "TYPE_GHOST",
    "DRAGON": "TYPE_DRAGON",
    "DARK": "TYPE_DARK",
    "STEEL": "TYPE_STEEL",
}


def escape_c_string(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def read_csv(path: pathlib.Path) -> List[Tuple[str, str, str]]:
    rows: List[Tuple[str, str, str]] = []
    seen_pairs = set()
    with path.open(newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        for row in reader:
            message = (row.get("message") or "").strip()
            type1 = (row.get("type1") or "").strip().upper()
            type2 = (row.get("type2") or "").strip().upper()
            if not message or not type1 or not type2:
                raise SystemExit(f"Invalid row in {path}: {row!r}")
            if type1 not in TYPE_MAP:
                raise SystemExit(f"Unknown type '{type1}' in {path}")
            if type2 not in TYPE_MAP:
                raise SystemExit(f"Unknown type '{type2}' in {path}")
            key = tuple(sorted((type1, type2)))
            if key in seen_pairs:
                raise SystemExit(f"Duplicate type pair {key} in {path}")
            seen_pairs.add(key)
            rows.append((message, type1, type2))
    return rows


def write_c_file(path: pathlib.Path, rows: List[Tuple[str, str, str]]) -> None:
    with path.open("w", encoding="utf-8") as handle:
        handle.write("// Auto-generated by tools/build_type_hint_table.py — do not edit.\n")
        handle.write('#include "global.h"\n')
        handle.write('#include "type_selection.h"\n')
        handle.write('#include "constants/type.h"\n\n')
        handle.write("const TypeHintDefinition gTypeHintTable[] = {\n")
        for message, type1, type2 in rows:
            msg_literal = escape_c_string(message)
            handle.write("    {\n")
            handle.write(f"        .message = _({msg_literal}),\n")
            handle.write(f"        .type1 = {TYPE_MAP[type1]},\n")
            handle.write(f"        .type2 = {TYPE_MAP[type2]},\n")
            handle.write("    },\n")
        handle.write("};\n\n")
        handle.write("const u32 gTypeHintCount = ARRAY_COUNT(gTypeHintTable);\n")


def main(argv: List[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("csv", type=pathlib.Path, help="Path to docs/type_choices.csv")
    parser.add_argument("out", type=pathlib.Path, help="Output C file path")
    args = parser.parse_args(argv)

    rows = read_csv(args.csv)
    if not rows:
        raise SystemExit(f"{args.csv} contains no hint rows.")

    write_c_file(args.out, rows)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
