#ifndef GUARD_MUNCHLAX_SPAWN_H
#define GUARD_MUNCHLAX_SPAWN_H

#define MUNCHLAX_SPAWN_CHANCE 1
#define MUNCHLAX_SPAWN_CHANCE_DENOM 2048
#define MUNCHLAX_SPAWN_LEVEL 1

#endif // GUARD_MUNCHLAX_SPAWN_H
