#!/usr/bin/env python3
import argparse
import csv
import sys


MAX_PALETTE_ID = 12


def load_shiny_palette_csv(path):
    with open(path, newline="") as csv_file:
        reader = csv.DictReader(csv_file)
        if reader.fieldnames is None:
            raise ValueError("CSV header is missing")
        required = {"id", "name", "shiny_palette_id"}
        missing = required - set(reader.fieldnames)
        if missing:
            raise ValueError(f"CSV missing columns: {', '.join(sorted(missing))}")

        rows = []
        for row in reader:
            if not row:
                continue
            try:
                monster_id = int(row["id"])
            except (TypeError, ValueError) as exc:
                raise ValueError(f"Invalid id value: {row.get('id')}") from exc
            try:
                palette_id = int(row["shiny_palette_id"])
            except (TypeError, ValueError) as exc:
                raise ValueError(
                    f"Invalid shiny_palette_id value: {row.get('shiny_palette_id')}"
                ) from exc
            rows.append((monster_id, palette_id))

    if not rows:
        raise ValueError("CSV has no data rows")

    seen_ids = set()
    max_id = -1
    for monster_id, palette_id in rows:
        if monster_id < 0:
            raise ValueError(f"Negative id value: {monster_id}")
        if monster_id in seen_ids:
            raise ValueError(f"Duplicate id value: {monster_id}")
        if palette_id < 0 or palette_id > MAX_PALETTE_ID:
            raise ValueError(
                f"Palette id out of range (0-{MAX_PALETTE_ID}): {palette_id}"
            )
        seen_ids.add(monster_id)
        if monster_id > max_id:
            max_id = monster_id

    expected_count = max_id + 1
    if len(rows) != expected_count:
        missing = sorted(set(range(expected_count)) - seen_ids)
        raise ValueError(f"Missing ids in CSV: {missing[:10]}")

    values = [0] * expected_count
    for monster_id, palette_id in rows:
        values[monster_id] = palette_id

    return values


def write_table(values, output_path, input_path):
    with open(output_path, "w", newline="\n") as out:
        out.write("// Auto-generated by rogue_files/gen_shiny_palette_table.py\n")
        out.write(f"// Source: {input_path}\n\n")
        out.write('#include "global.h"\n')
        out.write('#include "constants/monster.h"\n')
        out.write('#include "shiny_palette_table.h"\n\n')
        out.write("const u8 gMonsterShinyPalette[MONSTER_MAX] = {\n")
        for i, value in enumerate(values):
            if i % 16 == 0:
                out.write("    ")
            out.write(f"{value},")
            if i % 16 == 15 or i == len(values) - 1:
                out.write("\n")
            else:
                out.write(" ")
        out.write("};\n")


def main():
    parser = argparse.ArgumentParser(
        description="Generate shiny palette lookup table from CSV."
    )
    parser.add_argument("--input", required=True, help="Path to shiny_palette.csv")
    parser.add_argument("--output", required=True, help="Path to output .c file")
    args = parser.parse_args()

    try:
        values = load_shiny_palette_csv(args.input)
        write_table(values, args.output, args.input)
    except ValueError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
