#include "global.h"
#include "globaldata.h"
#include "monster_gfx.h"

#include "data/ax/decoy.h"
#include "data/ax/statue.h"
#include "data/ax/weavile.h"
#include "data/ax/riolu.h"
#include "data/ax/lucario.h"
#include "data/ax/bonsly.h"
#include "data/ax/mimejr.h"
#include "data/ax/joltik.h"
#include "data/ax/galvantula.h"
