// Auto-generated by tools/build_type_hint_table.py — do not edit.
#include "global.h"
#include "type_selection.h"
#include "constants/type.h"

const TypeHintDefinition gTypeHintTable[] = {
    {
        .message = _("A path marked by gentle restlessness, settling into a disciplined resolve."),
        .type1 = TYPE_BUG,
        .type2 = TYPE_FIGHTING,
    },
    {
        .message = _("A path where light drifts circle above, carrying a sense of subtle agility."),
        .type1 = TYPE_BUG,
        .type2 = TYPE_FLYING,
    },
    {
        .message = _("A path wrapped in a soft hush, shaped by an unseen presence moving just ahead."),
        .type1 = TYPE_BUG,
        .type2 = TYPE_GHOST,
    },
    {
        .message = _("A path rooted in stirring earth, steady and grounded beneath each step."),
        .type1 = TYPE_BUG,
        .type2 = TYPE_GROUND,
    },
    {
        .message = _("A path touched by a mild quiver, calm yet quietly shifting."),
        .type1 = TYPE_BUG,
        .type2 = TYPE_NORMAL,
    },
    {
        .message = _("A path veiled in quiet tension, curling through an uncertain stillness."),
        .type1 = TYPE_BUG,
        .type2 = TYPE_POISON,
    },
    {
        .message = _("A path shaped by subtle rhythm, blended with a weighty, patient strength."),
        .type1 = TYPE_BUG,
        .type2 = TYPE_ROCK,
    },
    {
        .message = _("A path where fine structure hums beneath a delicate wandering motion."),
        .type1 = TYPE_BUG,
        .type2 = TYPE_STEEL,
    },
    {
        .message = _("A path crossed by a muted shadow moving under roaming curiosity."),
        .type1 = TYPE_BUG,
        .type2 = TYPE_DARK,
    },
    {
        .message = _("A path stirred by an old pulse, coiling within a fleeting skitter."),
        .type1 = TYPE_BUG,
        .type2 = TYPE_DRAGON,
    },
    {
        .message = _("A path flickering softly through barely shifting air."),
        .type1 = TYPE_BUG,
        .type2 = TYPE_ELECTRIC,
    },
    {
        .message = _("A path warmed by a dancing flicker beneath a living motion."),
        .type1 = TYPE_BUG,
        .type2 = TYPE_FIRE,
    },
    {
        .message = _("A path where tender growth sways with faint restless energy."),
        .type1 = TYPE_BUG,
        .type2 = TYPE_GRASS,
    },
    {
        .message = _("A path marked by crisp stillness forming around a gentle movement."),
        .type1 = TYPE_BUG,
        .type2 = TYPE_ICE,
    },
    {
        .message = _("A path brushed by thoughtful murmurs alongside a curious drift."),
        .type1 = TYPE_BUG,
        .type2 = TYPE_PSYCHIC,
    },
    {
        .message = _("A path carried by a calm ripple holding a faint scuttling impression."),
        .type1 = TYPE_BUG,
        .type2 = TYPE_WATER,
    },
    {
        .message = _("A path held by quiet firmness merging with rising motion."),
        .type1 = TYPE_FIGHTING,
        .type2 = TYPE_FLYING,
    },
    {
        .message = _("A path steady with rhythmic focus, softened by a gentle fading presence."),
        .type1 = TYPE_FIGHTING,
        .type2 = TYPE_GHOST,
    },
    {
        .message = _("A path grounded by a determined calm settling into solid force."),
        .type1 = TYPE_FIGHTING,
        .type2 = TYPE_GROUND,
    },
    {
        .message = _("A path warmed by simple steadiness growing into firm resolve."),
        .type1 = TYPE_FIGHTING,
        .type2 = TYPE_NORMAL,
    },
    {
        .message = _("A path lined with soft unease beneath a determined air."),
        .type1 = TYPE_FIGHTING,
        .type2 = TYPE_POISON,
    },
    {
        .message = _("A path steadied by patient weight circling focused intent."),
        .type1 = TYPE_FIGHTING,
        .type2 = TYPE_ROCK,
    },
    {
        .message = _("A path shaped by quiet discipline forming subtly rigid stillness."),
        .type1 = TYPE_FIGHTING,
        .type2 = TYPE_STEEL,
    },
    {
        .message = _("A path deepened by a firm breath that settles into muted shadow."),
        .type1 = TYPE_FIGHTING,
        .type2 = TYPE_DARK,
    },
    {
        .message = _("A path coiled by a deep current beneath practiced strength."),
        .type1 = TYPE_FIGHTING,
        .type2 = TYPE_DRAGON,
    },
    {
        .message = _("A path flickering with faint vibration under steady focus."),
        .type1 = TYPE_FIGHTING,
        .type2 = TYPE_ELECTRIC,
    },
    {
        .message = _("A path tempered by gentle heat blended with restrained determination."),
        .type1 = TYPE_FIGHTING,
        .type2 = TYPE_FIRE,
    },
    {
        .message = _("A path rooted in living calm beneath a firm stance."),
        .type1 = TYPE_FIGHTING,
        .type2 = TYPE_GRASS,
    },
    {
        .message = _("A path cooled by sharp clarity tightening quiet discipline."),
        .type1 = TYPE_FIGHTING,
        .type2 = TYPE_ICE,
    },
    {
        .message = _("A path steadied by mindful presence rising into quiet energy."),
        .type1 = TYPE_FIGHTING,
        .type2 = TYPE_PSYCHIC,
    },
    {
        .message = _("A path softened by gentle flow easing persistent focus."),
        .type1 = TYPE_FIGHTING,
        .type2 = TYPE_WATER,
    },
    {
        .message = _("A path merging drifting lightness with a quiet, fading presence."),
        .type1 = TYPE_FLYING,
        .type2 = TYPE_GHOST,
    },
    {
        .message = _("A path settled by wandering breeze grounding into steady earth."),
        .type1 = TYPE_FLYING,
        .type2 = TYPE_GROUND,
    },
    {
        .message = _("A path softened by plain openness shifting into gentle motion."),
        .type1 = TYPE_FLYING,
        .type2 = TYPE_NORMAL,
    },
    {
        .message = _("A path threaded with thin unease beneath a wandering calm."),
        .type1 = TYPE_FLYING,
        .type2 = TYPE_POISON,
    },
    {
        .message = _("A path resting loose flutter against steady weight."),
        .type1 = TYPE_FLYING,
        .type2 = TYPE_ROCK,
    },
    {
        .message = _("A path carried by formed stillness holding drifting ease."),
        .type1 = TYPE_FLYING,
        .type2 = TYPE_STEEL,
    },
    {
        .message = _("A path moving beneath a dim veil crossing roaming stillness."),
        .type1 = TYPE_FLYING,
        .type2 = TYPE_DARK,
    },
    {
        .message = _("A path widened by a circling breath touching old quiet strength."),
        .type1 = TYPE_FLYING,
        .type2 = TYPE_DRAGON,
    },
    {
        .message = _("A path glowing with bright flicker gliding through open space."),
        .type1 = TYPE_FLYING,
        .type2 = TYPE_ELECTRIC,
    },
    {
        .message = _("A path warmed by whispering air moving freely overhead."),
        .type1 = TYPE_FLYING,
        .type2 = TYPE_FIRE,
    },
    {
        .message = _("A path overgrown softly, steadying a wandering breath."),
        .type1 = TYPE_FLYING,
        .type2 = TYPE_GRASS,
    },
    {
        .message = _("A path held in crisp openness with delicate motion."),
        .type1 = TYPE_FLYING,
        .type2 = TYPE_ICE,
    },
    {
        .message = _("A path stretched by calm intuition expanding into open space."),
        .type1 = TYPE_FLYING,
        .type2 = TYPE_PSYCHIC,
    },
    {
        .message = _("A path flowing gently across a quiet surface."),
        .type1 = TYPE_FLYING,
        .type2 = TYPE_WATER,
    },
    {
        .message = _("A path lined with dim echo lingering across settling ground."),
        .type1 = TYPE_GHOST,
        .type2 = TYPE_GROUND,
    },
    {
        .message = _("A path spread with plain quiet resting beneath a fading trace."),
        .type1 = TYPE_GHOST,
        .type2 = TYPE_NORMAL,
    },
    {
        .message = _("A path passing through soft blur drifting within uncertain stillness."),
        .type1 = TYPE_GHOST,
        .type2 = TYPE_POISON,
    },
    {
        .message = _("A path where quiet trace settles against unmoving weight."),
        .type1 = TYPE_GHOST,
        .type2 = TYPE_ROCK,
    },
    {
        .message = _("A path folded by muted ring into rigid calm."),
        .type1 = TYPE_GHOST,
        .type2 = TYPE_STEEL,
    },
    {
        .message = _("A path deepened by stillness settling behind a quiet veil."),
        .type1 = TYPE_GHOST,
        .type2 = TYPE_DARK,
    },
    {
        .message = _("A path coiling slow ancient calm beneath fading shapes."),
        .type1 = TYPE_GHOST,
        .type2 = TYPE_DRAGON,
    },
    {
        .message = _("A path humming with faint vibration behind pale silence."),
        .type1 = TYPE_GHOST,
        .type2 = TYPE_ELECTRIC,
    },
    {
        .message = _("A path warmed by low stirring glowing against empty hush."),
        .type1 = TYPE_GHOST,
        .type2 = TYPE_FIRE,
    },
    {
        .message = _("A path covered in gentle green hush over drifting echo."),
        .type1 = TYPE_GHOST,
        .type2 = TYPE_GRASS,
    },
    {
        .message = _("A path touched by delicate clarity meeting fading presence."),
        .type1 = TYPE_GHOST,
        .type2 = TYPE_ICE,
    },
    {
        .message = _("A path brushed by light thought over fading impression."),
        .type1 = TYPE_GHOST,
        .type2 = TYPE_PSYCHIC,
    },
    {
        .message = _("A path rippling quietly through hollow calm."),
        .type1 = TYPE_GHOST,
        .type2 = TYPE_WATER,
    },
    {
        .message = _("A path deepening steady base beneath simple calm."),
        .type1 = TYPE_GROUND,
        .type2 = TYPE_NORMAL,
    },
    {
        .message = _("A path heavy with muted weight blending into slight unease."),
        .type1 = TYPE_GROUND,
        .type2 = TYPE_POISON,
    },
    {
        .message = _("A path formed by firm weight meeting patient stillness."),
        .type1 = TYPE_GROUND,
        .type2 = TYPE_ROCK,
    },
    {
        .message = _("A path standing in shaped presence against quiet foundation."),
        .type1 = TYPE_GROUND,
        .type2 = TYPE_STEEL,
    },
    {
        .message = _("A path dimmed by heaviness resting beside deeper shade."),
        .type1 = TYPE_GROUND,
        .type2 = TYPE_DARK,
    },
    {
        .message = _("A path anchored by deep pulse sweeping through presence."),
        .type1 = TYPE_GROUND,
        .type2 = TYPE_DRAGON,
    },
    {
        .message = _("A path humming with small vibration in settled dust."),
        .type1 = TYPE_GROUND,
        .type2 = TYPE_ELECTRIC,
    },
    {
        .message = _("A path resting in soft warmth beneath level earth."),
        .type1 = TYPE_GROUND,
        .type2 = TYPE_FIRE,
    },
    {
        .message = _("A path rooted in living calm grounding into steady breath."),
        .type1 = TYPE_GROUND,
        .type2 = TYPE_GRASS,
    },
    {
        .message = _("A path cooled by chilled clarity tightening settled weight."),
        .type1 = TYPE_GROUND,
        .type2 = TYPE_ICE,
    },
    {
        .message = _("A path anchored by steady thought holding quiet depth."),
        .type1 = TYPE_GROUND,
        .type2 = TYPE_PSYCHIC,
    },
    {
        .message = _("A path smoothed by calm tide over steady earth."),
        .type1 = TYPE_GROUND,
        .type2 = TYPE_WATER,
    },
    {
        .message = _("A path carrying gentle plainness holding fading residue."),
        .type1 = TYPE_NORMAL,
        .type2 = TYPE_POISON,
    },
    {
        .message = _("A path settling in simple stillness into gentle weight."),
        .type1 = TYPE_NORMAL,
        .type2 = TYPE_ROCK,
    },
    {
        .message = _("A path ordered quietly along simple calm."),
        .type1 = TYPE_NORMAL,
        .type2 = TYPE_STEEL,
    },
    {
        .message = _("A path dim with hush lingering beneath ordinary quiet."),
        .type1 = TYPE_NORMAL,
        .type2 = TYPE_DARK,
    },
    {
        .message = _("A path pulsing calmly through steady simplicity."),
        .type1 = TYPE_NORMAL,
        .type2 = TYPE_DRAGON,
    },
    {
        .message = _("A path tinged by faint tingle stirring beneath plain air."),
        .type1 = TYPE_NORMAL,
        .type2 = TYPE_ELECTRIC,
    },
    {
        .message = _("A path warming with small rising heat meeting simple ease."),
        .type1 = TYPE_NORMAL,
        .type2 = TYPE_FIRE,
    },
    {
        .message = _("A path resting with soft growth beside quiet constancy."),
        .type1 = TYPE_NORMAL,
        .type2 = TYPE_GRASS,
    },
    {
        .message = _("A path cooled by crisp clarity settling on ordinary stillness."),
        .type1 = TYPE_NORMAL,
        .type2 = TYPE_ICE,
    },
    {
        .message = _("A path brushed with thoughtful glow over gentle simplicity."),
        .type1 = TYPE_NORMAL,
        .type2 = TYPE_PSYCHIC,
    },
    {
        .message = _("A path softened by modest flow through plain air."),
        .type1 = TYPE_NORMAL,
        .type2 = TYPE_WATER,
    },
    {
        .message = _("A path softened by drifting haze resting on patient weight."),
        .type1 = TYPE_POISON,
        .type2 = TYPE_ROCK,
    },
    {
        .message = _("A path bending faint distortion around rigid form."),
        .type1 = TYPE_POISON,
        .type2 = TYPE_STEEL,
    },
    {
        .message = _("A path resting with dim blur within deeper shade."),
        .type1 = TYPE_POISON,
        .type2 = TYPE_DARK,
    },
    {
        .message = _("A path curling slowly through ancient calm."),
        .type1 = TYPE_POISON,
        .type2 = TYPE_DRAGON,
    },
    {
        .message = _("A path flickering beneath muted haze."),
        .type1 = TYPE_POISON,
        .type2 = TYPE_ELECTRIC,
    },
    {
        .message = _("A path glowing low warmth through dissolving presence."),
        .type1 = TYPE_POISON,
        .type2 = TYPE_FIRE,
    },
    {
        .message = _("A path rising through tender growth beneath unclear veil."),
        .type1 = TYPE_POISON,
        .type2 = TYPE_GRASS,
    },
    {
        .message = _("A path cooled by pale clarity against unstable calm."),
        .type1 = TYPE_POISON,
        .type2 = TYPE_ICE,
    },
    {
        .message = _("A path brushing quiet distortion along thoughtful stillness."),
        .type1 = TYPE_POISON,
        .type2 = TYPE_PSYCHIC,
    },
    {
        .message = _("A path moving gentle wave through dissolving air."),
        .type1 = TYPE_POISON,
        .type2 = TYPE_WATER,
    },
    {
        .message = _("A path steadied by deep weight beside soft shadow."),
        .type1 = TYPE_ROCK,
        .type2 = TYPE_DARK,
    },
    {
        .message = _("A path winding ancient pulse beneath firm shape."),
        .type1 = TYPE_ROCK,
        .type2 = TYPE_DRAGON,
    },
    {
        .message = _("A path dancing with faint flicker across solid calm."),
        .type1 = TYPE_ROCK,
        .type2 = TYPE_ELECTRIC,
    },
    {
        .message = _("A path glowing warm hint behind heavy presence."),
        .type1 = TYPE_ROCK,
        .type2 = TYPE_FIRE,
    },
    {
        .message = _("A path softened by tender overgrowth against unyielding form."),
        .type1 = TYPE_ROCK,
        .type2 = TYPE_GRASS,
    },
    {
        .message = _("A path resting in crisp stillness atop unmoving weight."),
        .type1 = TYPE_ROCK,
        .type2 = TYPE_ICE,
    },
    {
        .message = _("A path humming thoughtfully within solid quiet."),
        .type1 = TYPE_ROCK,
        .type2 = TYPE_PSYCHIC,
    },
    {
        .message = _("A path touched by smooth wave brushing grounded stone."),
        .type1 = TYPE_ROCK,
        .type2 = TYPE_WATER,
    },
    {
        .message = _("A path lingering with muted shade shaped by rigid lines."),
        .type1 = TYPE_STEEL,
        .type2 = TYPE_DARK,
    },
};

const u32 gTypeHintCount = ARRAY_COUNT(gTypeHintTable);
