// Auto-generated by scripts/build_type_boss_table.py — do not edit.
#include "global.h"
#include "type_selection.h"
#include "constants/monster.h"
#include "constants/move_id.h"
#include "constants/type.h"

const TypeBossPool gTypeBossTable[NUM_TYPES] = {
    [TYPE_NONE] = {
        .species = {MONSTER_NONE, MONSTER_NONE},
        .minions = {
            {MONSTER_NONE, MONSTER_NONE},
            {MONSTER_NONE, MONSTER_NONE},
        },
        .moves = {
            {MOVE_NOTHING, MOVE_NOTHING, MOVE_NOTHING, MOVE_NOTHING},
            {MOVE_NOTHING, MOVE_NOTHING, MOVE_NOTHING, MOVE_NOTHING},
        },
        .hasCustomMoves = {FALSE, FALSE},
        .minionMoves = {
            {
                {MOVE_NOTHING, MOVE_NOTHING, MOVE_NOTHING, MOVE_NOTHING},
                {MOVE_NOTHING, MOVE_NOTHING, MOVE_NOTHING, MOVE_NOTHING},
            },
            {
                {MOVE_NOTHING, MOVE_NOTHING, MOVE_NOTHING, MOVE_NOTHING},
                {MOVE_NOTHING, MOVE_NOTHING, MOVE_NOTHING, MOVE_NOTHING},
            },
        },
        .minionHasCustomMoves = {
            {FALSE, FALSE},
            {FALSE, FALSE},
        },
        .bossStatTiers = {
            {STAT_TIER_MEDIUM, STAT_TIER_MEDIUM, STAT_TIER_MEDIUM, STAT_TIER_MEDIUM, STAT_TIER_MEDIUM},
            {STAT_TIER_MEDIUM, STAT_TIER_MEDIUM, STAT_TIER_MEDIUM, STAT_TIER_MEDIUM, STAT_TIER_MEDIUM},
        },
        .minionStatTiers = {
            {
                {STAT_TIER_MEDIUM, STAT_TIER_MEDIUM, STAT_TIER_MEDIUM, STAT_TIER_MEDIUM, STAT_TIER_MEDIUM},
                {STAT_TIER_MEDIUM, STAT_TIER_MEDIUM, STAT_TIER_MEDIUM, STAT_TIER_MEDIUM, STAT_TIER_MEDIUM},
            },
            {
                {STAT_TIER_MEDIUM, STAT_TIER_MEDIUM, STAT_TIER_MEDIUM, STAT_TIER_MEDIUM, STAT_TIER_MEDIUM},
                {STAT_TIER_MEDIUM, STAT_TIER_MEDIUM, STAT_TIER_MEDIUM, STAT_TIER_MEDIUM, STAT_TIER_MEDIUM},
            },
        },
        .count = 0,
    },
    [TYPE_NORMAL] = {
        .species = {MONSTER_MEWTWO, MONSTER_MEW},
        .minions = {
            {MONSTER_TAUROS, MONSTER_URSARING},
            {MONSTER_TOGETIC, MONSTER_PORYGON2},
        },
        .moves = {
            {MOVE_PSYCHIC, MOVE_THUNDERBOLT, MOVE_BARRIER, MOVE_SWIFT},
            {MOVE_PSYCHIC, MOVE_REFLECT, MOVE_MEGA_PUNCH, MOVE_METRONOME},
        },
        .hasCustomMoves = {TRUE, TRUE},
        .minionMoves = {
            {
                {MOVE_STRENGTH, MOVE_TAKE_DOWN, MOVE_SCARY_FACE, MOVE_PURSUIT},
                {MOVE_SLASH, MOVE_STRENGTH, MOVE_FURY_SWIPES, MOVE_EARTHQUAKE},
            },
            {
                {MOVE_METRONOME, MOVE_ANCIENTPOWER, MOVE_ENCORE, MOVE_SAFEGUARD},
                {MOVE_TRI_ATTACK, MOVE_ICE_BEAM, MOVE_PSYCHIC, MOVE_AGILITY},
            },
        },
        .minionHasCustomMoves = {
            {TRUE, TRUE},
            {TRUE, TRUE},
        },
        .bossStatTiers = {
            {STAT_TIER_MEDIUM, STAT_TIER_MEDIUM, STAT_TIER_HIGH, STAT_TIER_MEDIUM, STAT_TIER_MEDIUM},
            {STAT_TIER_MEDIUM, STAT_TIER_MEDIUM, STAT_TIER_MEDIUM, STAT_TIER_MEDIUM, STAT_TIER_MEDIUM},
        },
        .minionStatTiers = {
            {
                {STAT_TIER_MEDIUM, STAT_TIER_HIGH, STAT_TIER_LOW, STAT_TIER_HIGH, STAT_TIER_MEDIUM},
                {STAT_TIER_MEDIUM, STAT_TIER_HIGH, STAT_TIER_MEDIUM, STAT_TIER_MEDIUM, STAT_TIER_MEDIUM},
            },
            {
                {STAT_TIER_MEDIUM, STAT_TIER_LOW, STAT_TIER_MEDIUM, STAT_TIER_HIGH, STAT_TIER_HIGH},
                {STAT_TIER_MEDIUM, STAT_TIER_MEDIUM, STAT_TIER_HIGH, STAT_TIER_MEDIUM, STAT_TIER_HIGH},
            },
        },
        .count = 2,
    },
    [TYPE_FIRE] = {
        .species = {MONSTER_MOLTRES, MONSTER_ENTEI},
        .minions = {
            {MONSTER_CHARIZARD, MONSTER_TYPHLOSION},
            {MONSTER_FLAREON, MONSTER_FLAREON},
        },
        .moves = {
            {MOVE_FLAMETHROWER, MOVE_WING_ATTACK, MOVE_AGILITY, MOVE_FIRE_SPIN},
            {MOVE_FLAMETHROWER, MOVE_STOMP, MOVE_ROAR, MOVE_FIRE_SPIN},
        },
        .hasCustomMoves = {TRUE, TRUE},
        .minionMoves = {
            {
                {MOVE_FLAMETHROWER, MOVE_WING_ATTACK, MOVE_SLASH, MOVE_SMOKESCREEN},
                {MOVE_FLAMETHROWER, MOVE_SWIFT, MOVE_QUICK_ATTACK, MOVE_SMOKESCREEN},
            },
            {
                {MOVE_FLAMETHROWER, MOVE_BITE, MOVE_QUICK_ATTACK, MOVE_SAND_ATTACK},
                {MOVE_FLAMETHROWER, MOVE_BITE, MOVE_QUICK_ATTACK, MOVE_SAND_ATTACK},
            },
        },
        .minionHasCustomMoves = {
            {TRUE, TRUE},
            {TRUE, TRUE},
        },
        .bossStatTiers = {
            {STAT_TIER_MEDIUM, STAT_TIER_HIGH, STAT_TIER_HIGH, STAT_TIER_MEDIUM, STAT_TIER_MEDIUM},
            {STAT_TIER_MEDIUM, STAT_TIER_HIGH, STAT_TIER_MEDIUM, STAT_TIER_MEDIUM, STAT_TIER_LOW},
        },
        .minionStatTiers = {
            {
                {STAT_TIER_MEDIUM, STAT_TIER_MEDIUM, STAT_TIER_HIGH, STAT_TIER_MEDIUM, STAT_TIER_MEDIUM},
                {STAT_TIER_MEDIUM, STAT_TIER_MEDIUM, STAT_TIER_HIGH, STAT_TIER_MEDIUM, STAT_TIER_MEDIUM},
            },
            {
                {STAT_TIER_MEDIUM, STAT_TIER_HIGH, STAT_TIER_MEDIUM, STAT_TIER_LOW, STAT_TIER_HIGH},
                {STAT_TIER_MEDIUM, STAT_TIER_HIGH, STAT_TIER_MEDIUM, STAT_TIER_LOW, STAT_TIER_HIGH},
            },
        },
        .count = 2,
    },
    [TYPE_WATER] = {
        .species = {MONSTER_SUICUNE, MONSTER_KYOGRE},
        .minions = {
            {MONSTER_VAPOREON, MONSTER_VAPOREON},
            {MONSTER_GOREBYSS, MONSTER_HUNTAIL},
        },
        .moves = {
            {MOVE_SURF, MOVE_AURORA_BEAM, MOVE_CALM_MIND, MOVE_MIRROR_COAT},
            {MOVE_SURF, MOVE_ICE_BEAM, MOVE_CALM_MIND, MOVE_THUNDER},
        },
        .hasCustomMoves = {TRUE, TRUE},
        .minionMoves = {
            {
                {MOVE_SURF, MOVE_AURORA_BEAM, MOVE_ACID_ARMOR, MOVE_QUICK_ATTACK},
                {MOVE_SURF, MOVE_AURORA_BEAM, MOVE_ACID_ARMOR, MOVE_QUICK_ATTACK},
            },
            {
                {MOVE_SURF, MOVE_PSYCHIC, MOVE_AGILITY, MOVE_AMNESIA},
                {MOVE_CRUNCH, MOVE_WATER_PULSE, MOVE_SCARY_FACE, MOVE_BITE},
            },
        },
        .minionHasCustomMoves = {
            {TRUE, TRUE},
            {TRUE, TRUE},
        },
        .bossStatTiers = {
            {STAT_TIER_MEDIUM, STAT_TIER_LOW, STAT_TIER_MEDIUM, STAT_TIER_HIGH, STAT_TIER_HIGH},
            {STAT_TIER_MEDIUM, STAT_TIER_MEDIUM, STAT_TIER_HIGH, STAT_TIER_MEDIUM, STAT_TIER_HIGH},
        },
        .minionStatTiers = {
            {
                {STAT_TIER_MEDIUM, STAT_TIER_LOW, STAT_TIER_HIGH, STAT_TIER_LOW, STAT_TIER_HIGH},
                {STAT_TIER_MEDIUM, STAT_TIER_LOW, STAT_TIER_HIGH, STAT_TIER_LOW, STAT_TIER_HIGH},
            },
            {
                {STAT_TIER_MEDIUM, STAT_TIER_MEDIUM, STAT_TIER_HIGH, STAT_TIER_HIGH, STAT_TIER_LOW},
                {STAT_TIER_MEDIUM, STAT_TIER_HIGH, STAT_TIER_MEDIUM, STAT_TIER_HIGH, STAT_TIER_LOW},
            },
        },
        .count = 2,
    },
    [TYPE_GRASS] = {
        .species = {MONSTER_CELEBI, MONSTER_VENUSAUR},
        .minions = {
            {MONSTER_TROPIUS, MONSTER_EXEGGUTOR},
            {MONSTER_MEGANIUM, MONSTER_SCEPTILE},
        },
        .moves = {
            {MOVE_PSYCHIC, MOVE_FUTURE_SIGHT, MOVE_ANCIENTPOWER, MOVE_SOLARBEAM},
            {MOVE_SOLARBEAM, MOVE_SLEEP_POWDER, MOVE_SLUDGE_BOMB, MOVE_EARTHQUAKE},
        },
        .hasCustomMoves = {TRUE, TRUE},
        .minionMoves = {
            {
                {MOVE_RAZOR_LEAF, MOVE_GUST, MOVE_STUN_SPORE, MOVE_AERIAL_ACE},
                {MOVE_PSYCHIC, MOVE_EGG_BOMB, MOVE_STUN_SPORE, MOVE_REFLECT},
            },
            {
                {MOVE_RAZOR_LEAF, MOVE_BODY_SLAM, MOVE_LIGHT_SCREEN, MOVE_POISONPOWDER},
                {MOVE_LEAF_BLADE, MOVE_QUICK_ATTACK, MOVE_AGILITY, MOVE_PURSUIT},
            },
        },
        .minionHasCustomMoves = {
            {TRUE, TRUE},
            {TRUE, TRUE},
        },
        .bossStatTiers = {
            {STAT_TIER_MEDIUM, STAT_TIER_MEDIUM, STAT_TIER_MEDIUM, STAT_TIER_MEDIUM, STAT_TIER_MEDIUM},
            {STAT_TIER_MEDIUM, STAT_TIER_MEDIUM, STAT_TIER_HIGH, STAT_TIER_MEDIUM, STAT_TIER_HIGH},
        },
        .minionStatTiers = {
            {
                {STAT_TIER_MEDIUM, STAT_TIER_LOW, STAT_TIER_LOW, STAT_TIER_MEDIUM, STAT_TIER_MEDIUM},
                {STAT_TIER_MEDIUM, STAT_TIER_MEDIUM, STAT_TIER_HIGH, STAT_TIER_MEDIUM, STAT_TIER_LOW},
            },
            {
                {STAT_TIER_MEDIUM, STAT_TIER_MEDIUM, STAT_TIER_MEDIUM, STAT_TIER_HIGH, STAT_TIER_HIGH},
                {STAT_TIER_MEDIUM, STAT_TIER_MEDIUM, STAT_TIER_HIGH, STAT_TIER_LOW, STAT_TIER_MEDIUM},
            },
        },
        .count = 2,
    },
    [TYPE_ELECTRIC] = {
        .species = {MONSTER_ZAPDOS, MONSTER_RAIKOU},
        .minions = {
            {MONSTER_RAICHU, MONSTER_MANECTRIC},
            {MONSTER_JOLTEON, MONSTER_JOLTEON},
        },
        .moves = {
            {MOVE_DRILL_PECK, MOVE_THUNDERBOLT, MOVE_THUNDER_WAVE, MOVE_AGILITY},
            {MOVE_THUNDERBOLT, MOVE_SPARK, MOVE_BITE, MOVE_REFLECT},
        },
        .hasCustomMoves = {TRUE, TRUE},
        .minionMoves = {
            {
                {MOVE_THUNDERBOLT, MOVE_QUICK_ATTACK, MOVE_THUNDER_WAVE, MOVE_IRON_TAIL},
                {MOVE_SPARK, MOVE_BITE, MOVE_ROAR, MOVE_QUICK_ATTACK},
            },
            {
                {MOVE_THUNDERBOLT, MOVE_DOUBLE_KICK, MOVE_AGILITY, MOVE_PIN_MISSILE},
                {MOVE_THUNDERBOLT, MOVE_DOUBLE_KICK, MOVE_AGILITY, MOVE_PIN_MISSILE},
            },
        },
        .minionHasCustomMoves = {
            {TRUE, TRUE},
            {TRUE, TRUE},
        },
        .bossStatTiers = {
            {STAT_TIER_MEDIUM, STAT_TIER_MEDIUM, STAT_TIER_HIGH, STAT_TIER_MEDIUM, STAT_TIER_MEDIUM},
            {STAT_TIER_MEDIUM, STAT_TIER_MEDIUM, STAT_TIER_HIGH, STAT_TIER_LOW, STAT_TIER_HIGH},
        },
        .minionStatTiers = {
            {
                {STAT_TIER_MEDIUM, STAT_TIER_HIGH, STAT_TIER_HIGH, STAT_TIER_LOW, STAT_TIER_MEDIUM},
                {STAT_TIER_MEDIUM, STAT_TIER_MEDIUM, STAT_TIER_HIGH, STAT_TIER_LOW, STAT_TIER_LOW},
            },
            {
                {STAT_TIER_MEDIUM, STAT_TIER_LOW, STAT_TIER_HIGH, STAT_TIER_LOW, STAT_TIER_HIGH},
                {STAT_TIER_MEDIUM, STAT_TIER_LOW, STAT_TIER_HIGH, STAT_TIER_LOW, STAT_TIER_HIGH},
            },
        },
        .count = 2,
    },
    [TYPE_ICE] = {
        .species = {MONSTER_ARTICUNO, MONSTER_REGICE},
        .minions = {
            {MONSTER_DEWGONG, MONSTER_CLOYSTER},
            {MONSTER_GLALIE, MONSTER_WALREIN},
        },
        .moves = {
            {MOVE_ICE_BEAM, MOVE_GUST, MOVE_AGILITY, MOVE_MIND_READER},
            {MOVE_ICE_BEAM, MOVE_AMNESIA, MOVE_ICY_WIND, MOVE_EXPLOSION},
        },
        .hasCustomMoves = {TRUE, TRUE},
        .minionMoves = {
            {
                {MOVE_AURORA_BEAM, MOVE_SURF, MOVE_ICE_BEAM, MOVE_ENCORE},
                {MOVE_AURORA_BEAM, MOVE_PROTECT, MOVE_SPIKE_CANNON, MOVE_SUPERSONIC},
            },
            {
                {MOVE_ICE_BEAM, MOVE_CRUNCH, MOVE_HEADBUTT, MOVE_BITE},
                {MOVE_SURF, MOVE_BODY_SLAM, MOVE_ICE_BEAM, MOVE_ENCORE},
            },
        },
        .minionHasCustomMoves = {
            {TRUE, TRUE},
            {TRUE, TRUE},
        },
        .bossStatTiers = {
            {STAT_TIER_MEDIUM, STAT_TIER_MEDIUM, STAT_TIER_MEDIUM, STAT_TIER_HIGH, STAT_TIER_HIGH},
            {STAT_TIER_MEDIUM, STAT_TIER_LOW, STAT_TIER_HIGH, STAT_TIER_HIGH, STAT_TIER_HIGH},
        },
        .minionStatTiers = {
            {
                {STAT_TIER_MEDIUM, STAT_TIER_LOW, STAT_TIER_LOW, STAT_TIER_MEDIUM, STAT_TIER_HIGH},
                {STAT_TIER_MEDIUM, STAT_TIER_HIGH, STAT_TIER_MEDIUM, STAT_TIER_HIGH, STAT_TIER_LOW},
            },
            {
                {STAT_TIER_MEDIUM, STAT_TIER_MEDIUM, STAT_TIER_MEDIUM, STAT_TIER_MEDIUM, STAT_TIER_MEDIUM},
                {STAT_TIER_MEDIUM, STAT_TIER_MEDIUM, STAT_TIER_MEDIUM, STAT_TIER_MEDIUM, STAT_TIER_MEDIUM},
            },
        },
        .count = 2,
    },
    [TYPE_FIGHTING] = {
        .species = {MONSTER_MACHAMP, MONSTER_MEDICHAM},
        .minions = {
            {MONSTER_HITMONLEE, MONSTER_HITMONCHAN},
            {MONSTER_BRELOOM, MONSTER_HARIYAMA},
        },
        .moves = {
            {MOVE_CROSS_CHOP, MOVE_VITAL_THROW, MOVE_ROCK_SLIDE, MOVE_BULK_UP},
            {MOVE_HI_JUMP_KICK, MOVE_PSYCHIC, MOVE_DETECT, MOVE_ICE_PUNCH},
        },
        .hasCustomMoves = {TRUE, TRUE},
        .minionMoves = {
            {
                {MOVE_HI_JUMP_KICK, MOVE_BRICK_BREAK, MOVE_BULK_UP, MOVE_FOCUS_ENERGY},
                {MOVE_SKY_UPPERCUT, MOVE_THUNDERPUNCH, MOVE_ICE_PUNCH, MOVE_AGILITY},
            },
            {
                {MOVE_SKY_UPPERCUT, MOVE_MACH_PUNCH, MOVE_MEGA_PUNCH, MOVE_STUN_SPORE},
                {MOVE_CROSS_CHOP, MOVE_BELLY_DRUM, MOVE_FAKE_OUT, MOVE_KNOCK_OFF},
            },
        },
        .minionHasCustomMoves = {
            {TRUE, TRUE},
            {TRUE, TRUE},
        },
        .bossStatTiers = {
            {STAT_TIER_MEDIUM, STAT_TIER_HIGH, STAT_TIER_LOW, STAT_TIER_MEDIUM, STAT_TIER_MEDIUM},
            {STAT_TIER_MEDIUM, STAT_TIER_LOW, STAT_TIER_LOW, STAT_TIER_MEDIUM, STAT_TIER_MEDIUM},
        },
        .minionStatTiers = {
            {
                {STAT_TIER_MEDIUM, STAT_TIER_HIGH, STAT_TIER_LOW, STAT_TIER_LOW, STAT_TIER_HIGH},
                {STAT_TIER_MEDIUM, STAT_TIER_HIGH, STAT_TIER_LOW, STAT_TIER_MEDIUM, STAT_TIER_HIGH},
            },
            {
                {STAT_TIER_MEDIUM, STAT_TIER_HIGH, STAT_TIER_LOW, STAT_TIER_MEDIUM, STAT_TIER_LOW},
                {STAT_TIER_MEDIUM, STAT_TIER_HIGH, STAT_TIER_LOW, STAT_TIER_LOW, STAT_TIER_LOW},
            },
        },
        .count = 2,
    },
    [TYPE_POISON] = {
        .species = {MONSTER_MUK, MONSTER_CROBAT},
        .minions = {
            {MONSTER_WEEZING, MONSTER_SWALOT},
            {MONSTER_SEVIPER, MONSTER_ARBOK},
        },
        .moves = {
            {MOVE_SLUDGE_BOMB, MOVE_ACID_ARMOR, MOVE_MINIMIZE, MOVE_SHADOW_BALL},
            {MOVE_SLUDGE_BOMB, MOVE_WING_ATTACK, MOVE_CONFUSE_RAY, MOVE_BITE},
        },
        .hasCustomMoves = {TRUE, TRUE},
        .minionMoves = {
            {
                {MOVE_SLUDGE_BOMB, MOVE_EXPLOSION, MOVE_SMOKESCREEN, MOVE_HAZE},
                {MOVE_SLUDGE_BOMB, MOVE_AMNESIA, MOVE_BODY_SLAM, MOVE_YAWN},
            },
            {
                {MOVE_POISON_FANG, MOVE_CRUNCH, MOVE_GLARE, MOVE_SCREECH},
                {MOVE_ACID, MOVE_GLARE, MOVE_BITE, MOVE_WRAP},
            },
        },
        .minionHasCustomMoves = {
            {TRUE, TRUE},
            {TRUE, TRUE},
        },
        .bossStatTiers = {
            {STAT_TIER_MEDIUM, STAT_TIER_HIGH, STAT_TIER_LOW, STAT_TIER_MEDIUM, STAT_TIER_HIGH},
            {STAT_TIER_MEDIUM, STAT_TIER_HIGH, STAT_TIER_LOW, STAT_TIER_MEDIUM, STAT_TIER_MEDIUM},
        },
        .minionStatTiers = {
            {
                {STAT_TIER_MEDIUM, STAT_TIER_HIGH, STAT_TIER_MEDIUM, STAT_TIER_HIGH, STAT_TIER_LOW},
                {STAT_TIER_MEDIUM, STAT_TIER_MEDIUM, STAT_TIER_MEDIUM, STAT_TIER_MEDIUM, STAT_TIER_MEDIUM},
            },
            {
                {STAT_TIER_MEDIUM, STAT_TIER_HIGH, STAT_TIER_HIGH, STAT_TIER_LOW, STAT_TIER_LOW},
                {STAT_TIER_MEDIUM, STAT_TIER_HIGH, STAT_TIER_LOW, STAT_TIER_MEDIUM, STAT_TIER_MEDIUM},
            },
        },
        .count = 2,
    },
    [TYPE_GROUND] = {
        .species = {MONSTER_GROUDON, MONSTER_CLAYDOL},
        .minions = {
            {MONSTER_RHYDON, MONSTER_ONIX},
            {MONSTER_SOLROCK, MONSTER_LUNATONE},
        },
        .moves = {
            {MOVE_EARTHQUAKE, MOVE_ANCIENTPOWER, MOVE_SLASH, MOVE_BULK_UP},
            {MOVE_ANCIENTPOWER, MOVE_PSYCHIC, MOVE_HYPER_BEAM, MOVE_REFLECT},
        },
        .hasCustomMoves = {TRUE, TRUE},
        .minionMoves = {
            {
                {MOVE_EARTHQUAKE, MOVE_ROCK_BLAST, MOVE_SCARY_FACE, MOVE_PROTECT},
                {MOVE_ROCK_SLIDE, MOVE_ROCK_THROW, MOVE_SCREECH, MOVE_BIND},
            },
            {
                {MOVE_ROCK_SLIDE, MOVE_PSYCHIC, MOVE_LIGHT_SCREEN, MOVE_EXPLOSION},
                {MOVE_PSYCHIC, MOVE_ROCK_THROW, MOVE_HYPNOSIS, MOVE_COSMIC_POWER},
            },
        },
        .minionHasCustomMoves = {
            {TRUE, TRUE},
            {TRUE, TRUE},
        },
        .bossStatTiers = {
            {STAT_TIER_MEDIUM, STAT_TIER_HIGH, STAT_TIER_MEDIUM, STAT_TIER_HIGH, STAT_TIER_MEDIUM},
            {STAT_TIER_MEDIUM, STAT_TIER_LOW, STAT_TIER_LOW, STAT_TIER_HIGH, STAT_TIER_HIGH},
        },
        .minionStatTiers = {
            {
                {STAT_TIER_MEDIUM, STAT_TIER_HIGH, STAT_TIER_LOW, STAT_TIER_HIGH, STAT_TIER_LOW},
                {STAT_TIER_MEDIUM, STAT_TIER_LOW, STAT_TIER_LOW, STAT_TIER_HIGH, STAT_TIER_LOW},
            },
            {
                {STAT_TIER_MEDIUM, STAT_TIER_HIGH, STAT_TIER_LOW, STAT_TIER_MEDIUM, STAT_TIER_LOW},
                {STAT_TIER_MEDIUM, STAT_TIER_LOW, STAT_TIER_HIGH, STAT_TIER_LOW, STAT_TIER_MEDIUM},
            },
        },
        .count = 2,
    },
    [TYPE_FLYING] = {
        .species = {MONSTER_HO_OH, MONSTER_RAYQUAZA},
        .minions = {
            {MONSTER_SWELLOW, MONSTER_PIDGEOT},
            {MONSTER_AERODACTYL, MONSTER_ALTARIA},
        },
        .moves = {
            {MOVE_SACRED_FIRE, MOVE_GUST, MOVE_FLY, MOVE_FIRE_BLAST},
            {MOVE_DRAGON_CLAW, MOVE_CRUNCH, MOVE_HYPER_BEAM, MOVE_DRAGON_DANCE},
        },
        .hasCustomMoves = {TRUE, TRUE},
        .minionMoves = {
            {
                {MOVE_WING_ATTACK, MOVE_QUICK_ATTACK, MOVE_AERIAL_ACE, MOVE_FOCUS_ENERGY},
                {MOVE_WING_ATTACK, MOVE_SAND_ATTACK, MOVE_QUICK_ATTACK, MOVE_FEATHERDANCE},
            },
            {
                {MOVE_ROCK_SLIDE, MOVE_WING_ATTACK, MOVE_AGILITY, MOVE_BITE},
                {MOVE_DRAGONBREATH, MOVE_SING, MOVE_SAFEGUARD, MOVE_FLY},
            },
        },
        .minionHasCustomMoves = {
            {TRUE, TRUE},
            {TRUE, TRUE},
        },
        .bossStatTiers = {
            {STAT_TIER_MEDIUM, STAT_TIER_HIGH, STAT_TIER_HIGH, STAT_TIER_MEDIUM, STAT_TIER_HIGH},
            {STAT_TIER_MEDIUM, STAT_TIER_HIGH, STAT_TIER_HIGH, STAT_TIER_MEDIUM, STAT_TIER_MEDIUM},
        },
        .minionStatTiers = {
            {
                {STAT_TIER_MEDIUM, STAT_TIER_HIGH, STAT_TIER_LOW, STAT_TIER_LOW, STAT_TIER_LOW},
                {STAT_TIER_MEDIUM, STAT_TIER_MEDIUM, STAT_TIER_LOW, STAT_TIER_MEDIUM, STAT_TIER_LOW},
            },
            {
                {STAT_TIER_MEDIUM, STAT_TIER_HIGH, STAT_TIER_LOW, STAT_TIER_LOW, STAT_TIER_MEDIUM},
                {STAT_TIER_MEDIUM, STAT_TIER_LOW, STAT_TIER_LOW, STAT_TIER_HIGH, STAT_TIER_HIGH},
            },
        },
        .count = 2,
    },
    [TYPE_PSYCHIC] = {
        .species = {MONSTER_LUGIA, MONSTER_DEOXYS_NORMAL},
        .minions = {
            {MONSTER_XATU, MONSTER_STARMIE},
            {MONSTER_DEOXYS_ATTACK, MONSTER_DEOXYS_DEFENSE},
        },
        .moves = {
            {MOVE_AEROBLAST, MOVE_HYDRO_PUMP, MOVE_PSYCHIC, MOVE_SAFEGUARD},
            {MOVE_PSYCHIC, MOVE_COSMIC_POWER, MOVE_THUNDERBOLT, MOVE_ICE_BEAM},
        },
        .hasCustomMoves = {TRUE, TRUE},
        .minionMoves = {
            {
                {MOVE_PSYCHIC, MOVE_CONFUSE_RAY, MOVE_FUTURE_SIGHT, MOVE_TELEPORT},
                {MOVE_SURF, MOVE_THUNDERBOLT, MOVE_PSYCHIC, MOVE_ICE_BEAM},
            },
            {
                {MOVE_PSYCHIC, MOVE_PURSUIT, MOVE_COSMIC_POWER, MOVE_SUPERPOWER},
                {MOVE_PSYCHIC, MOVE_PURSUIT, MOVE_COSMIC_POWER, MOVE_PROTECT},
            },
        },
        .minionHasCustomMoves = {
            {TRUE, TRUE},
            {TRUE, TRUE},
        },
        .bossStatTiers = {
            {STAT_TIER_MEDIUM, STAT_TIER_MEDIUM, STAT_TIER_MEDIUM, STAT_TIER_HIGH, STAT_TIER_HIGH},
            {STAT_TIER_MEDIUM, STAT_TIER_HIGH, STAT_TIER_HIGH, STAT_TIER_LOW, STAT_TIER_LOW},
        },
        .minionStatTiers = {
            {
                {STAT_TIER_MEDIUM, STAT_TIER_MEDIUM, STAT_TIER_HIGH, STAT_TIER_LOW, STAT_TIER_LOW},
                {STAT_TIER_MEDIUM, STAT_TIER_MEDIUM, STAT_TIER_HIGH, STAT_TIER_MEDIUM, STAT_TIER_MEDIUM},
            },
            {
                {STAT_TIER_MEDIUM, STAT_TIER_HIGH, STAT_TIER_HIGH, STAT_TIER_LOW, STAT_TIER_LOW},
                {STAT_TIER_MEDIUM, STAT_TIER_LOW, STAT_TIER_LOW, STAT_TIER_HIGH, STAT_TIER_HIGH},
            },
        },
        .count = 2,
    },
    [TYPE_BUG] = {
        .species = {MONSTER_HERACROSS, MONSTER_SCIZOR},
        .minions = {
            {MONSTER_BEEDRILL, MONSTER_BUTTERFREE},
            {MONSTER_SCYTHER, MONSTER_SCYTHER},
        },
        .moves = {
            {MOVE_MEGAHORN, MOVE_BRICK_BREAK, MOVE_ROCK_SLIDE, MOVE_BULK_UP},
            {MOVE_SILVER_WIND, MOVE_STEEL_WING, MOVE_DOUBLE_TEAM, MOVE_AERIAL_ACE},
        },
        .hasCustomMoves = {TRUE, TRUE},
        .minionMoves = {
            {
                {MOVE_TWINEEDLE, MOVE_PIN_MISSILE, MOVE_FOCUS_ENERGY, MOVE_AGILITY},
                {MOVE_SILVER_WIND, MOVE_CONFUSION, MOVE_SLEEP_POWDER, MOVE_WHIRLWIND},
            },
            {
                {MOVE_WING_ATTACK, MOVE_FURY_CUTTER, MOVE_AGILITY, MOVE_SWORDS_DANCE},
                {MOVE_WING_ATTACK, MOVE_FURY_CUTTER, MOVE_AGILITY, MOVE_SWORDS_DANCE},
            },
        },
        .minionHasCustomMoves = {
            {TRUE, TRUE},
            {TRUE, TRUE},
        },
        .bossStatTiers = {
            {STAT_TIER_MEDIUM, STAT_TIER_HIGH, STAT_TIER_LOW, STAT_TIER_MEDIUM, STAT_TIER_HIGH},
            {STAT_TIER_MEDIUM, STAT_TIER_HIGH, STAT_TIER_LOW, STAT_TIER_HIGH, STAT_TIER_MEDIUM},
        },
        .minionStatTiers = {
            {
                {STAT_TIER_MEDIUM, STAT_TIER_HIGH, STAT_TIER_LOW, STAT_TIER_LOW, STAT_TIER_HIGH},
                {STAT_TIER_MEDIUM, STAT_TIER_LOW, STAT_TIER_HIGH, STAT_TIER_LOW, STAT_TIER_HIGH},
            },
            {
                {STAT_TIER_MEDIUM, STAT_TIER_HIGH, STAT_TIER_LOW, STAT_TIER_MEDIUM, STAT_TIER_MEDIUM},
                {STAT_TIER_MEDIUM, STAT_TIER_HIGH, STAT_TIER_LOW, STAT_TIER_MEDIUM, STAT_TIER_MEDIUM},
            },
        },
        .count = 2,
    },
    [TYPE_ROCK] = {
        .species = {MONSTER_REGIROCK, MONSTER_TYRANITAR},
        .minions = {
            {MONSTER_CRADILY, MONSTER_ARMALDO},
            {MONSTER_KABUTOPS, MONSTER_OMASTAR},
        },
        .moves = {
            {MOVE_ROCK_SLIDE, MOVE_SUPERPOWER, MOVE_EXPLOSION, MOVE_CURSE},
            {MOVE_CRUNCH, MOVE_ROCK_SLIDE, MOVE_EARTHQUAKE, MOVE_DRAGON_DANCE},
        },
        .hasCustomMoves = {TRUE, TRUE},
        .minionMoves = {
            {
                {MOVE_ANCIENTPOWER, MOVE_RAZOR_LEAF, MOVE_CONFUSE_RAY, MOVE_AMNESIA},
                {MOVE_ANCIENTPOWER, MOVE_SLASH, MOVE_FURY_CUTTER, MOVE_PROTECT},
            },
            {
                {MOVE_SLASH, MOVE_ANCIENTPOWER, MOVE_WATERFALL, MOVE_SAND_ATTACK},
                {MOVE_SURF, MOVE_SPIKE_CANNON, MOVE_PROTECT, MOVE_BITE},
            },
        },
        .minionHasCustomMoves = {
            {TRUE, TRUE},
            {TRUE, TRUE},
        },
        .bossStatTiers = {
            {STAT_TIER_MEDIUM, STAT_TIER_HIGH, STAT_TIER_LOW, STAT_TIER_HIGH, STAT_TIER_HIGH},
            {STAT_TIER_MEDIUM, STAT_TIER_HIGH, STAT_TIER_MEDIUM, STAT_TIER_HIGH, STAT_TIER_MEDIUM},
        },
        .minionStatTiers = {
            {
                {STAT_TIER_MEDIUM, STAT_TIER_MEDIUM, STAT_TIER_MEDIUM, STAT_TIER_HIGH, STAT_TIER_HIGH},
                {STAT_TIER_MEDIUM, STAT_TIER_HIGH, STAT_TIER_LOW, STAT_TIER_HIGH, STAT_TIER_MEDIUM},
            },
            {
                {STAT_TIER_MEDIUM, STAT_TIER_HIGH, STAT_TIER_LOW, STAT_TIER_HIGH, STAT_TIER_MEDIUM},
                {STAT_TIER_MEDIUM, STAT_TIER_LOW, STAT_TIER_HIGH, STAT_TIER_HIGH, STAT_TIER_MEDIUM},
            },
        },
        .count = 2,
    },
    [TYPE_GHOST] = {
        .species = {MONSTER_GENGAR, MONSTER_DUSCLOPS},
        .minions = {
            {MONSTER_BANETTE, MONSTER_SHEDINJA},
            {MONSTER_SABLEYE, MONSTER_MISDREAVUS},
        },
        .moves = {
            {MOVE_SHADOW_BALL, MOVE_HYPNOSIS, MOVE_DREAM_EATER, MOVE_THUNDERBOLT},
            {MOVE_SHADOW_PUNCH, MOVE_WILL_O_WISP, MOVE_EARTHQUAKE, MOVE_PROTECT},
        },
        .hasCustomMoves = {TRUE, TRUE},
        .minionMoves = {
            {
                {MOVE_SHADOW_BALL, MOVE_WILL_O_WISP, MOVE_KNOCK_OFF, MOVE_SCREECH},
                {MOVE_SHADOW_BALL, MOVE_FURY_CUTTER, MOVE_SWORDS_DANCE, MOVE_AGILITY},
            },
            {
                {MOVE_SHADOW_BALL, MOVE_FAINT_ATTACK, MOVE_NIGHT_SHADE, MOVE_CONFUSE_RAY},
                {MOVE_SHADOW_BALL, MOVE_PSYBEAM, MOVE_CONFUSE_RAY, MOVE_MEAN_LOOK},
            },
        },
        .minionHasCustomMoves = {
            {TRUE, TRUE},
            {TRUE, TRUE},
        },
        .bossStatTiers = {
            {STAT_TIER_MEDIUM, STAT_TIER_LOW, STAT_TIER_HIGH, STAT_TIER_LOW, STAT_TIER_MEDIUM},
            {STAT_TIER_MEDIUM, STAT_TIER_LOW, STAT_TIER_LOW, STAT_TIER_HIGH, STAT_TIER_HIGH},
        },
        .minionStatTiers = {
            {
                {STAT_TIER_MEDIUM, STAT_TIER_HIGH, STAT_TIER_MEDIUM, STAT_TIER_LOW, STAT_TIER_LOW},
                {STAT_TIER_MEDIUM, STAT_TIER_HIGH, STAT_TIER_LOW, STAT_TIER_LOW, STAT_TIER_LOW},
            },
            {
                {STAT_TIER_MEDIUM, STAT_TIER_MEDIUM, STAT_TIER_LOW, STAT_TIER_MEDIUM, STAT_TIER_LOW},
                {STAT_TIER_MEDIUM, STAT_TIER_LOW, STAT_TIER_HIGH, STAT_TIER_LOW, STAT_TIER_HIGH},
            },
        },
        .count = 2,
    },
    [TYPE_DRAGON] = {
        .species = {MONSTER_LATIAS, MONSTER_LATIOS},
        .minions = {
            {MONSTER_DRAGONITE, MONSTER_KINGDRA},
            {MONSTER_SALAMENCE, MONSTER_FLYGON},
        },
        .moves = {
            {MOVE_MIST_BALL, MOVE_DRAGONBREATH, MOVE_CALM_MIND, MOVE_ICE_BEAM},
            {MOVE_LUSTER_PURGE, MOVE_DRAGONBREATH, MOVE_CALM_MIND, MOVE_THUNDERBOLT},
        },
        .hasCustomMoves = {TRUE, TRUE},
        .minionMoves = {
            {
                {MOVE_WING_ATTACK, MOVE_THUNDER_WAVE, MOVE_DRAGON_CLAW, MOVE_AGILITY},
                {MOVE_HYDRO_PUMP, MOVE_TWISTER, MOVE_AGILITY, MOVE_ICE_BEAM},
            },
            {
                {MOVE_DRAGON_CLAW, MOVE_CRUNCH, MOVE_FLY, MOVE_DRAGON_DANCE},
                {MOVE_EARTHQUAKE, MOVE_DRAGONBREATH, MOVE_SANDSTORM, MOVE_CRUNCH},
            },
        },
        .minionHasCustomMoves = {
            {TRUE, TRUE},
            {TRUE, TRUE},
        },
        .bossStatTiers = {
            {STAT_TIER_MEDIUM, STAT_TIER_LOW, STAT_TIER_HIGH, STAT_TIER_MEDIUM, STAT_TIER_HIGH},
            {STAT_TIER_MEDIUM, STAT_TIER_MEDIUM, STAT_TIER_HIGH, STAT_TIER_LOW, STAT_TIER_HIGH},
        },
        .minionStatTiers = {
            {
                {STAT_TIER_MEDIUM, STAT_TIER_HIGH, STAT_TIER_HIGH, STAT_TIER_MEDIUM, STAT_TIER_MEDIUM},
                {STAT_TIER_MEDIUM, STAT_TIER_MEDIUM, STAT_TIER_MEDIUM, STAT_TIER_MEDIUM, STAT_TIER_MEDIUM},
            },
            {
                {STAT_TIER_MEDIUM, STAT_TIER_HIGH, STAT_TIER_HIGH, STAT_TIER_MEDIUM, STAT_TIER_MEDIUM},
                {STAT_TIER_MEDIUM, STAT_TIER_HIGH, STAT_TIER_MEDIUM, STAT_TIER_MEDIUM, STAT_TIER_MEDIUM},
            },
        },
        .count = 2,
    },
    [TYPE_DARK] = {
        .species = {MONSTER_ABSOL, MONSTER_SHIFTRY},
        .minions = {
            {MONSTER_SABLEYE, MONSTER_MIGHTYENA},
            {MONSTER_CRAWDAUNT, MONSTER_SHARPEDO},
        },
        .moves = {
            {MOVE_BITE, MOVE_SLASH, MOVE_SWORDS_DANCE, MOVE_QUICK_ATTACK},
            {MOVE_RAZOR_LEAF, MOVE_NATURE_POWER, MOVE_EXTRASENSORY, MOVE_FAKE_OUT},
        },
        .hasCustomMoves = {TRUE, TRUE},
        .minionMoves = {
            {
                {MOVE_SHADOW_BALL, MOVE_KNOCK_OFF, MOVE_NIGHT_SHADE, MOVE_CONFUSE_RAY},
                {MOVE_BITE, MOVE_CRUNCH, MOVE_HOWL, MOVE_SAND_ATTACK},
            },
            {
                {MOVE_CRABHAMMER, MOVE_CRUNCH, MOVE_SWORDS_DANCE, MOVE_PROTECT},
                {MOVE_CRUNCH, MOVE_WATER_PULSE, MOVE_SCREECH, MOVE_AGILITY},
            },
        },
        .minionHasCustomMoves = {
            {TRUE, TRUE},
            {TRUE, TRUE},
        },
        .bossStatTiers = {
            {STAT_TIER_MEDIUM, STAT_TIER_HIGH, STAT_TIER_MEDIUM, STAT_TIER_LOW, STAT_TIER_LOW},
            {STAT_TIER_MEDIUM, STAT_TIER_HIGH, STAT_TIER_MEDIUM, STAT_TIER_LOW, STAT_TIER_LOW},
        },
        .minionStatTiers = {
            {
                {STAT_TIER_MEDIUM, STAT_TIER_MEDIUM, STAT_TIER_LOW, STAT_TIER_MEDIUM, STAT_TIER_LOW},
                {STAT_TIER_MEDIUM, STAT_TIER_HIGH, STAT_TIER_LOW, STAT_TIER_MEDIUM, STAT_TIER_LOW},
            },
            {
                {STAT_TIER_MEDIUM, STAT_TIER_HIGH, STAT_TIER_HIGH, STAT_TIER_MEDIUM, STAT_TIER_LOW},
                {STAT_TIER_MEDIUM, STAT_TIER_HIGH, STAT_TIER_MEDIUM, STAT_TIER_LOW, STAT_TIER_LOW},
            },
        },
        .count = 2,
    },
    [TYPE_STEEL] = {
        .species = {MONSTER_REGISTEEL, MONSTER_JIRACHI},
        .minions = {
            {MONSTER_MAGNETON, MONSTER_SKARMORY},
            {MONSTER_METAGROSS, MONSTER_STEELIX},
        },
        .moves = {
            {MOVE_METAL_CLAW, MOVE_SUPERPOWER, MOVE_EXPLOSION, MOVE_CURSE},
            {MOVE_PSYCHIC, MOVE_SWIFT, MOVE_DOOM_DESIRE, MOVE_DOUBLE_EDGE},
        },
        .hasCustomMoves = {TRUE, TRUE},
        .minionMoves = {
            {
                {MOVE_THUNDERBOLT, MOVE_SUPERSONIC, MOVE_LOCK_ON, MOVE_ZAP_CANNON},
                {MOVE_STEEL_WING, MOVE_AGILITY, MOVE_SAND_ATTACK, MOVE_SWIFT},
            },
            {
                {MOVE_METEOR_MASH, MOVE_PSYCHIC, MOVE_AGILITY, MOVE_EARTHQUAKE},
                {MOVE_IRON_TAIL, MOVE_ROCK_SLIDE, MOVE_SANDSTORM, MOVE_SCREECH},
            },
        },
        .minionHasCustomMoves = {
            {TRUE, TRUE},
            {TRUE, TRUE},
        },
        .bossStatTiers = {
            {STAT_TIER_MEDIUM, STAT_TIER_LOW, STAT_TIER_LOW, STAT_TIER_HIGH, STAT_TIER_HIGH},
            {STAT_TIER_MEDIUM, STAT_TIER_MEDIUM, STAT_TIER_MEDIUM, STAT_TIER_MEDIUM, STAT_TIER_MEDIUM},
        },
        .minionStatTiers = {
            {
                {STAT_TIER_MEDIUM, STAT_TIER_LOW, STAT_TIER_HIGH, STAT_TIER_HIGH, STAT_TIER_MEDIUM},
                {STAT_TIER_MEDIUM, STAT_TIER_MEDIUM, STAT_TIER_LOW, STAT_TIER_HIGH, STAT_TIER_MEDIUM},
            },
            {
                {STAT_TIER_MEDIUM, STAT_TIER_HIGH, STAT_TIER_MEDIUM, STAT_TIER_HIGH, STAT_TIER_MEDIUM},
                {STAT_TIER_MEDIUM, STAT_TIER_MEDIUM, STAT_TIER_LOW, STAT_TIER_HIGH, STAT_TIER_LOW},
            },
        },
        .count = 2,
    },
};

const TypeBossWeatherPool gTypeBossWeatherTable[NUM_TYPES] = {
    [TYPE_NONE] = {
        .bosses = {
            {0},
            {0},
        },
        .count = 0,
    },
    [TYPE_NORMAL] = {
        .bosses = {
            { .enabled = FALSE, .weather = WEATHER_CLEAR, .chance = {0, 0, 0} },
            { .enabled = FALSE, .weather = WEATHER_CLEAR, .chance = {0, 0, 0} },
        },
        .count = 2,
    },
    [TYPE_FIRE] = {
        .bosses = {
            { .enabled = TRUE, .weather = WEATHER_SUNNY, .chance = {0, 600, 1000} },
            { .enabled = TRUE, .weather = WEATHER_SUNNY, .chance = {0, 600, 1000} },
        },
        .count = 2,
    },
    [TYPE_WATER] = {
        .bosses = {
            { .enabled = TRUE, .weather = WEATHER_FOG, .chance = {0, 600, 1000} },
            { .enabled = FALSE, .weather = WEATHER_CLEAR, .chance = {0, 0, 0} },
        },
        .count = 2,
    },
    [TYPE_GRASS] = {
        .bosses = {
            { .enabled = FALSE, .weather = WEATHER_CLEAR, .chance = {0, 0, 0} },
            { .enabled = TRUE, .weather = WEATHER_SUNNY, .chance = {0, 600, 1000} },
        },
        .count = 2,
    },
    [TYPE_ELECTRIC] = {
        .bosses = {
            { .enabled = FALSE, .weather = WEATHER_CLEAR, .chance = {0, 0, 0} },
            { .enabled = FALSE, .weather = WEATHER_CLEAR, .chance = {0, 0, 0} },
        },
        .count = 2,
    },
    [TYPE_ICE] = {
        .bosses = {
            { .enabled = TRUE, .weather = WEATHER_SNOW, .chance = {0, 600, 1000} },
            { .enabled = TRUE, .weather = WEATHER_HAIL, .chance = {0, 600, 1000} },
        },
        .count = 2,
    },
    [TYPE_FIGHTING] = {
        .bosses = {
            { .enabled = FALSE, .weather = WEATHER_CLEAR, .chance = {0, 0, 0} },
            { .enabled = FALSE, .weather = WEATHER_CLEAR, .chance = {0, 0, 0} },
        },
        .count = 2,
    },
    [TYPE_POISON] = {
        .bosses = {
            { .enabled = FALSE, .weather = WEATHER_CLEAR, .chance = {0, 0, 0} },
            { .enabled = FALSE, .weather = WEATHER_CLEAR, .chance = {0, 0, 0} },
        },
        .count = 2,
    },
    [TYPE_GROUND] = {
        .bosses = {
            { .enabled = FALSE, .weather = WEATHER_CLEAR, .chance = {0, 0, 0} },
            { .enabled = FALSE, .weather = WEATHER_CLEAR, .chance = {0, 0, 0} },
        },
        .count = 2,
    },
    [TYPE_FLYING] = {
        .bosses = {
            { .enabled = FALSE, .weather = WEATHER_CLEAR, .chance = {0, 0, 0} },
            { .enabled = FALSE, .weather = WEATHER_CLEAR, .chance = {0, 0, 0} },
        },
        .count = 2,
    },
    [TYPE_PSYCHIC] = {
        .bosses = {
            { .enabled = TRUE, .weather = WEATHER_FOG, .chance = {0, 600, 1000} },
            { .enabled = FALSE, .weather = WEATHER_CLEAR, .chance = {0, 0, 0} },
        },
        .count = 2,
    },
    [TYPE_BUG] = {
        .bosses = {
            { .enabled = FALSE, .weather = WEATHER_CLEAR, .chance = {0, 0, 0} },
            { .enabled = FALSE, .weather = WEATHER_CLEAR, .chance = {0, 0, 0} },
        },
        .count = 2,
    },
    [TYPE_ROCK] = {
        .bosses = {
            { .enabled = TRUE, .weather = WEATHER_SANDSTORM, .chance = {0, 600, 1000} },
            { .enabled = FALSE, .weather = WEATHER_CLEAR, .chance = {0, 0, 0} },
        },
        .count = 2,
    },
    [TYPE_GHOST] = {
        .bosses = {
            { .enabled = FALSE, .weather = WEATHER_CLEAR, .chance = {0, 0, 0} },
            { .enabled = FALSE, .weather = WEATHER_CLEAR, .chance = {0, 0, 0} },
        },
        .count = 2,
    },
    [TYPE_DRAGON] = {
        .bosses = {
            { .enabled = FALSE, .weather = WEATHER_CLEAR, .chance = {0, 0, 0} },
            { .enabled = FALSE, .weather = WEATHER_CLEAR, .chance = {0, 0, 0} },
        },
        .count = 2,
    },
    [TYPE_DARK] = {
        .bosses = {
            { .enabled = FALSE, .weather = WEATHER_CLEAR, .chance = {0, 0, 0} },
            { .enabled = FALSE, .weather = WEATHER_CLEAR, .chance = {0, 0, 0} },
        },
        .count = 2,
    },
    [TYPE_STEEL] = {
        .bosses = {
            { .enabled = FALSE, .weather = WEATHER_CLEAR, .chance = {0, 0, 0} },
            { .enabled = FALSE, .weather = WEATHER_CLEAR, .chance = {0, 0, 0} },
        },
        .count = 2,
    },
};
