// Auto-generated by scripts/build_type_boss_table.py — do not edit.
#include "global.h"
#include "type_selection.h"
#include "constants/monster.h"
#include "constants/type.h"

const TypeBossPool gTypeBossTable[NUM_TYPES] = {
    [TYPE_NONE] = {
        .species = {MONSTER_NONE, MONSTER_NONE},
        .count = 0,
    },
    [TYPE_NORMAL] = {
        .species = {MONSTER_MEWTWO, MONSTER_MEW},
        .count = 2,
    },
    [TYPE_FIRE] = {
        .species = {MONSTER_MOLTRES, MONSTER_ENTEI},
        .count = 2,
    },
    [TYPE_WATER] = {
        .species = {MONSTER_SUICUNE, MONSTER_KYOGRE},
        .count = 2,
    },
    [TYPE_GRASS] = {
        .species = {MONSTER_CELEBI, MONSTER_VENUSAUR},
        .count = 2,
    },
    [TYPE_ELECTRIC] = {
        .species = {MONSTER_ZAPDOS, MONSTER_RAIKOU},
        .count = 2,
    },
    [TYPE_ICE] = {
        .species = {MONSTER_ARTICUNO, MONSTER_REGICE},
        .count = 2,
    },
    [TYPE_FIGHTING] = {
        .species = {MONSTER_MACHAMP, MONSTER_MEDICHAM},
        .count = 2,
    },
    [TYPE_POISON] = {
        .species = {MONSTER_MUK, MONSTER_CROBAT},
        .count = 2,
    },
    [TYPE_GROUND] = {
        .species = {MONSTER_GROUDON, MONSTER_CLAYDOL},
        .count = 2,
    },
    [TYPE_FLYING] = {
        .species = {MONSTER_HO_OH, MONSTER_RAYQUAZA},
        .count = 2,
    },
    [TYPE_PSYCHIC] = {
        .species = {MONSTER_LUGIA, MONSTER_DEOXYS_NORMAL},
        .count = 2,
    },
    [TYPE_BUG] = {
        .species = {MONSTER_HERACROSS, MONSTER_PINSIR},
        .count = 2,
    },
    [TYPE_ROCK] = {
        .species = {MONSTER_REGIROCK, MONSTER_TYRANITAR},
        .count = 2,
    },
    [TYPE_GHOST] = {
        .species = {MONSTER_GENGAR, MONSTER_DUSCLOPS},
        .count = 2,
    },
    [TYPE_DRAGON] = {
        .species = {MONSTER_LATIAS, MONSTER_LATIOS},
        .count = 2,
    },
    [TYPE_DARK] = {
        .species = {MONSTER_ABSOL, MONSTER_SHIFTRY},
        .count = 2,
    },
    [TYPE_STEEL] = {
        .species = {MONSTER_REGISTEEL, MONSTER_JIRACHI},
        .count = 2,
    },
};
