// Auto-generated by tools/build_type_hint_table.py — do not edit.
#include "global.h"
#include "type_selection.h"
#include "constants/type.h"

const TypeHintDefinition gTypeHintTable[] = {
    {
        .message = _("A gentle restlessness moves beneath a quiet resolve"),
        .type1 = TYPE_BUG,
        .type2 = TYPE_FIGHTING,
    },
    {
        .message = _("A light drift circles around something subtly agile"),
        .type1 = TYPE_BUG,
        .type2 = TYPE_FLYING,
    },
    {
        .message = _("A soft hush weaves through an unseen presence"),
        .type1 = TYPE_BUG,
        .type2 = TYPE_GHOST,
    },
    {
        .message = _("A faint stirring settles into the steady ground"),
        .type1 = TYPE_BUG,
        .type2 = TYPE_GROUND,
    },
    {
        .message = _("A mild quiver ripples through an otherwise simple calm"),
        .type1 = TYPE_BUG,
        .type2 = TYPE_NORMAL,
    },
    {
        .message = _("A quiet tension curls through an uncertain stillness"),
        .type1 = TYPE_BUG,
        .type2 = TYPE_POISON,
    },
    {
        .message = _("A subtle rhythm blends with a weighty patience"),
        .type1 = TYPE_BUG,
        .type2 = TYPE_ROCK,
    },
    {
        .message = _("Fine structure hums beneath a delicate wandering motion"),
        .type1 = TYPE_BUG,
        .type2 = TYPE_STEEL,
    },
    {
        .message = _("A muted shadow passes under a roaming curiosity"),
        .type1 = TYPE_BUG,
        .type2 = TYPE_DARK,
    },
    {
        .message = _("An old pulse stirs within a fleeting skitter"),
        .type1 = TYPE_BUG,
        .type2 = TYPE_DRAGON,
    },
    {
        .message = _("A soft flicker winds through a barely shifting air"),
        .type1 = TYPE_BUG,
        .type2 = TYPE_ELECTRIC,
    },
    {
        .message = _("A warm flicker dances beneath a living motion"),
        .type1 = TYPE_BUG,
        .type2 = TYPE_FIRE,
    },
    {
        .message = _("A tender growth sways with a faint restless energy"),
        .type1 = TYPE_BUG,
        .type2 = TYPE_GRASS,
    },
    {
        .message = _("A crisp stillness forms around a gentle movement"),
        .type1 = TYPE_BUG,
        .type2 = TYPE_ICE,
    },
    {
        .message = _("A thoughtful murmur brushes alongside a curious drift"),
        .type1 = TYPE_BUG,
        .type2 = TYPE_PSYCHIC,
    },
    {
        .message = _("A calm ripple carries a faint scuttling impression"),
        .type1 = TYPE_BUG,
        .type2 = TYPE_WATER,
    },
    {
        .message = _("A quiet firmness merges with a rising motion"),
        .type1 = TYPE_FIGHTING,
        .type2 = TYPE_FLYING,
    },
    {
        .message = _("A steady rhythm blends with a gentle fading presence"),
        .type1 = TYPE_FIGHTING,
        .type2 = TYPE_GHOST,
    },
    {
        .message = _("A grounded force settles beneath a determined calm"),
        .type1 = TYPE_FIGHTING,
        .type2 = TYPE_GROUND,
    },
    {
        .message = _("A simple steadiness warms beneath a growing resolve"),
        .type1 = TYPE_FIGHTING,
        .type2 = TYPE_NORMAL,
    },
    {
        .message = _("A soft unease hangs beneath a determined air"),
        .type1 = TYPE_FIGHTING,
        .type2 = TYPE_POISON,
    },
    {
        .message = _("A patient weight steadies around a focused intent"),
        .type1 = TYPE_FIGHTING,
        .type2 = TYPE_ROCK,
    },
    {
        .message = _("A quiet discipline shapes a subtly rigid stillness"),
        .type1 = TYPE_FIGHTING,
        .type2 = TYPE_STEEL,
    },
    {
        .message = _("A firm breath deepens into a muted shadow"),
        .type1 = TYPE_FIGHTING,
        .type2 = TYPE_DARK,
    },
    {
        .message = _("A deep current coils beneath a practiced strength"),
        .type1 = TYPE_FIGHTING,
        .type2 = TYPE_DRAGON,
    },
    {
        .message = _("A faint vibration flickers under a steady focus"),
        .type1 = TYPE_FIGHTING,
        .type2 = TYPE_ELECTRIC,
    },
    {
        .message = _("A tempered heat blends with restrained determination"),
        .type1 = TYPE_FIGHTING,
        .type2 = TYPE_FIRE,
    },
    {
        .message = _("A living calm roots beneath a firm stance"),
        .type1 = TYPE_FIGHTING,
        .type2 = TYPE_GRASS,
    },
    {
        .message = _("A sharp clarity cools a quiet discipline"),
        .type1 = TYPE_FIGHTING,
        .type2 = TYPE_ICE,
    },
    {
        .message = _("A mindful presence steadies a rising energy"),
        .type1 = TYPE_FIGHTING,
        .type2 = TYPE_PSYCHIC,
    },
    {
        .message = _("A gentle flow softens a persistent focus"),
        .type1 = TYPE_FIGHTING,
        .type2 = TYPE_WATER,
    },
    {
        .message = _("A drifting lightness blends with a quiet fading"),
        .type1 = TYPE_FLYING,
        .type2 = TYPE_GHOST,
    },
    {
        .message = _("A wandering breeze settles into steady ground"),
        .type1 = TYPE_FLYING,
        .type2 = TYPE_GROUND,
    },
    {
        .message = _("A plain openness softens into gentle motion"),
        .type1 = TYPE_FLYING,
        .type2 = TYPE_NORMAL,
    },
    {
        .message = _("A thin unease threads through a wandering calm"),
        .type1 = TYPE_FLYING,
        .type2 = TYPE_POISON,
    },
    {
        .message = _("A loose flutter rests against a steady weight"),
        .type1 = TYPE_FLYING,
        .type2 = TYPE_ROCK,
    },
    {
        .message = _("A formed stillness carries a drifting ease"),
        .type1 = TYPE_FLYING,
        .type2 = TYPE_STEEL,
    },
    {
        .message = _("A dim veil moves beneath a roaming stillness"),
        .type1 = TYPE_FLYING,
        .type2 = TYPE_DARK,
    },
    {
        .message = _("A wide breath circles an old quiet strength"),
        .type1 = TYPE_FLYING,
        .type2 = TYPE_DRAGON,
    },
    {
        .message = _("A bright flicker glides through open space"),
        .type1 = TYPE_FLYING,
        .type2 = TYPE_ELECTRIC,
    },
    {
        .message = _("A warmed whisper moves through open air"),
        .type1 = TYPE_FLYING,
        .type2 = TYPE_FIRE,
    },
    {
        .message = _("A soft overgrowth steadies a wandering breath"),
        .type1 = TYPE_FLYING,
        .type2 = TYPE_GRASS,
    },
    {
        .message = _("A crisp openness hangs with delicate motion"),
        .type1 = TYPE_FLYING,
        .type2 = TYPE_ICE,
    },
    {
        .message = _("A calm intuition stretches into open space"),
        .type1 = TYPE_FLYING,
        .type2 = TYPE_PSYCHIC,
    },
    {
        .message = _("A gentle drift flows across a quiet surface"),
        .type1 = TYPE_FLYING,
        .type2 = TYPE_WATER,
    },
    {
        .message = _("A dim echo lingers across the settling ground"),
        .type1 = TYPE_GHOST,
        .type2 = TYPE_GROUND,
    },
    {
        .message = _("A plain quiet spreads beneath a fading trace"),
        .type1 = TYPE_GHOST,
        .type2 = TYPE_NORMAL,
    },
    {
        .message = _("A soft blur drifts through an uncertain stillness"),
        .type1 = TYPE_GHOST,
        .type2 = TYPE_POISON,
    },
    {
        .message = _("A quiet trace settles against unmoving weight"),
        .type1 = TYPE_GHOST,
        .type2 = TYPE_ROCK,
    },
    {
        .message = _("A muted ring folds into a rigid calm"),
        .type1 = TYPE_GHOST,
        .type2 = TYPE_STEEL,
    },
    {
        .message = _("A deep stillness settles behind a quiet veil"),
        .type1 = TYPE_GHOST,
        .type2 = TYPE_DARK,
    },
    {
        .message = _("A slow ancient calm coils beneath fading shapes"),
        .type1 = TYPE_GHOST,
        .type2 = TYPE_DRAGON,
    },
    {
        .message = _("A faint vibration hums behind a pale silence"),
        .type1 = TYPE_GHOST,
        .type2 = TYPE_ELECTRIC,
    },
    {
        .message = _("A low stirring glows against an empty hush"),
        .type1 = TYPE_GHOST,
        .type2 = TYPE_FIRE,
    },
    {
        .message = _("A gentle green hush covers a drifting echo"),
        .type1 = TYPE_GHOST,
        .type2 = TYPE_GRASS,
    },
    {
        .message = _("A delicate clarity meets a fading presence"),
        .type1 = TYPE_GHOST,
        .type2 = TYPE_ICE,
    },
    {
        .message = _("A light thought brushes a fading impression"),
        .type1 = TYPE_GHOST,
        .type2 = TYPE_PSYCHIC,
    },
    {
        .message = _("A quiet ripple moves through a hollow calm"),
        .type1 = TYPE_GHOST,
        .type2 = TYPE_WATER,
    },
    {
        .message = _("A steady base deepens beneath a simple calm"),
        .type1 = TYPE_GROUND,
        .type2 = TYPE_NORMAL,
    },
    {
        .message = _("A muted heaviness blends into a slight unease"),
        .type1 = TYPE_GROUND,
        .type2 = TYPE_POISON,
    },
    {
        .message = _("A firm weight meets a patient stillness"),
        .type1 = TYPE_GROUND,
        .type2 = TYPE_ROCK,
    },
    {
        .message = _("A shaped presence stands with a quiet foundation"),
        .type1 = TYPE_GROUND,
        .type2 = TYPE_STEEL,
    },
    {
        .message = _("A dim heaviness rests beside a deeper shade"),
        .type1 = TYPE_GROUND,
        .type2 = TYPE_DARK,
    },
    {
        .message = _("A deep pulse anchors a sweeping presence"),
        .type1 = TYPE_GROUND,
        .type2 = TYPE_DRAGON,
    },
    {
        .message = _("A small vibration hums in the settled dust"),
        .type1 = TYPE_GROUND,
        .type2 = TYPE_ELECTRIC,
    },
    {
        .message = _("A soft warmth rests beneath the level earth"),
        .type1 = TYPE_GROUND,
        .type2 = TYPE_FIRE,
    },
    {
        .message = _("A living calm roots into a grounded breath"),
        .type1 = TYPE_GROUND,
        .type2 = TYPE_GRASS,
    },
    {
        .message = _("A chilled clarity tightens around settled weight"),
        .type1 = TYPE_GROUND,
        .type2 = TYPE_ICE,
    },
    {
        .message = _("A steady thought anchors a quiet depth"),
        .type1 = TYPE_GROUND,
        .type2 = TYPE_PSYCHIC,
    },
    {
        .message = _("A calm tide smooths the steady earth"),
        .type1 = TYPE_GROUND,
        .type2 = TYPE_WATER,
    },
    {
        .message = _("A gentle plainness carries a fading residue"),
        .type1 = TYPE_NORMAL,
        .type2 = TYPE_POISON,
    },
    {
        .message = _("A simple stillness settles into gentle weight"),
        .type1 = TYPE_NORMAL,
        .type2 = TYPE_ROCK,
    },
    {
        .message = _("A quiet order lines a simple calm"),
        .type1 = TYPE_NORMAL,
        .type2 = TYPE_STEEL,
    },
    {
        .message = _("A dim hush lingers beneath an ordinary quiet"),
        .type1 = TYPE_NORMAL,
        .type2 = TYPE_DARK,
    },
    {
        .message = _("A calm pulse moves through steady simplicity"),
        .type1 = TYPE_NORMAL,
        .type2 = TYPE_DRAGON,
    },
    {
        .message = _("A faint tingle stirs beneath plain air"),
        .type1 = TYPE_NORMAL,
        .type2 = TYPE_ELECTRIC,
    },
    {
        .message = _("A small rising warmth meets simple ease"),
        .type1 = TYPE_NORMAL,
        .type2 = TYPE_FIRE,
    },
    {
        .message = _("A soft growth rests beside quiet constancy"),
        .type1 = TYPE_NORMAL,
        .type2 = TYPE_GRASS,
    },
    {
        .message = _("A cool clarity settles on an ordinary stillness"),
        .type1 = TYPE_NORMAL,
        .type2 = TYPE_ICE,
    },
    {
        .message = _("A thoughtful glow brushes a gentle simplicity"),
        .type1 = TYPE_NORMAL,
        .type2 = TYPE_PSYCHIC,
    },
    {
        .message = _("A modest flow softens the plain air"),
        .type1 = TYPE_NORMAL,
        .type2 = TYPE_WATER,
    },
    {
        .message = _("A drifting haze softens a patient weight"),
        .type1 = TYPE_POISON,
        .type2 = TYPE_ROCK,
    },
    {
        .message = _("A faint distortion bends around rigid form"),
        .type1 = TYPE_POISON,
        .type2 = TYPE_STEEL,
    },
    {
        .message = _("A dim blur rests within a deeper shade"),
        .type1 = TYPE_POISON,
        .type2 = TYPE_DARK,
    },
    {
        .message = _("A slow curl winds through ancient calm"),
        .type1 = TYPE_POISON,
        .type2 = TYPE_DRAGON,
    },
    {
        .message = _("A flicker moves beneath a muted haze"),
        .type1 = TYPE_POISON,
        .type2 = TYPE_ELECTRIC,
    },
    {
        .message = _("A low glow warms a dissolving presence"),
        .type1 = TYPE_POISON,
        .type2 = TYPE_FIRE,
    },
    {
        .message = _("A tender growth rises through an unclear veil"),
        .type1 = TYPE_POISON,
        .type2 = TYPE_GRASS,
    },
    {
        .message = _("A pale clarity cools an unstable calm"),
        .type1 = TYPE_POISON,
        .type2 = TYPE_ICE,
    },
    {
        .message = _("A quiet distortion brushes thoughtful stillness"),
        .type1 = TYPE_POISON,
        .type2 = TYPE_PSYCHIC,
    },
    {
        .message = _("A gentle wave moves through a dissolving air"),
        .type1 = TYPE_POISON,
        .type2 = TYPE_WATER,
    },
    {
        .message = _("A deep weight steadies beside a soft shadow"),
        .type1 = TYPE_ROCK,
        .type2 = TYPE_DARK,
    },
    {
        .message = _("An ancient pulse winds beneath a firm shape"),
        .type1 = TYPE_ROCK,
        .type2 = TYPE_DRAGON,
    },
    {
        .message = _("A faint flicker dances across a solid calm"),
        .type1 = TYPE_ROCK,
        .type2 = TYPE_ELECTRIC,
    },
    {
        .message = _("A warm hint glows behind heavy presence"),
        .type1 = TYPE_ROCK,
        .type2 = TYPE_FIRE,
    },
    {
        .message = _("A tender overgrowth softens unyielding form"),
        .type1 = TYPE_ROCK,
        .type2 = TYPE_GRASS,
    },
    {
        .message = _("A crisp stillness rests upon unmoving weight"),
        .type1 = TYPE_ROCK,
        .type2 = TYPE_ICE,
    },
    {
        .message = _("A thoughtful hum moves within solid quiet"),
        .type1 = TYPE_ROCK,
        .type2 = TYPE_PSYCHIC,
    },
    {
        .message = _("A smooth wave touches the grounded stone"),
        .type1 = TYPE_ROCK,
        .type2 = TYPE_WATER,
    },
    {
        .message = _("A muted shade lingers within rigid lines"),
        .type1 = TYPE_STEEL,
        .type2 = TYPE_DARK,
    },
};

const u32 gTypeHintCount = ARRAY_COUNT(gTypeHintTable);
