// Auto-generated by scripts/build_type_boss_table.py — do not edit.
#include "global.h"
#include "type_selection.h"
#include "constants/monster.h"
#include "constants/move_id.h"
#include "constants/type.h"

const TypeBossPool gTypeBossTable[NUM_TYPES] = {
    [TYPE_NONE] = {
        .species = {MONSTER_NONE, MONSTER_NONE},
        .minions = {
            {MONSTER_NONE, MONSTER_NONE},
            {MONSTER_NONE, MONSTER_NONE},
        },
        .moves = {
            {MOVE_NOTHING, MOVE_NOTHING, MOVE_NOTHING, MOVE_NOTHING},
            {MOVE_NOTHING, MOVE_NOTHING, MOVE_NOTHING, MOVE_NOTHING},
        },
        .hasCustomMoves = {FALSE, FALSE},
        .count = 0,
    },
    [TYPE_NORMAL] = {
        .species = {MONSTER_MEWTWO, MONSTER_MEW},
        .minions = {
            {MONSTER_TAUROS, MONSTER_URSARING},
            {MONSTER_TOGETIC, MONSTER_PORYGON2},
        },
        .moves = {
            {MOVE_SELFDESTRUCT, MOVE_NOTHING, MOVE_NOTHING, MOVE_NOTHING},
            {MOVE_SELFDESTRUCT, MOVE_NOTHING, MOVE_NOTHING, MOVE_NOTHING},
        },
        .hasCustomMoves = {TRUE, TRUE},
        .count = 2,
    },
    [TYPE_FIRE] = {
        .species = {MONSTER_MOLTRES, MONSTER_ENTEI},
        .minions = {
            {MONSTER_CHARIZARD, MONSTER_TYPHLOSION},
            {MONSTER_FLAREON, MONSTER_FLAREON},
        },
        .moves = {
            {MOVE_SELFDESTRUCT, MOVE_NOTHING, MOVE_NOTHING, MOVE_NOTHING},
            {MOVE_SELFDESTRUCT, MOVE_NOTHING, MOVE_NOTHING, MOVE_NOTHING},
        },
        .hasCustomMoves = {TRUE, TRUE},
        .count = 2,
    },
    [TYPE_WATER] = {
        .species = {MONSTER_SUICUNE, MONSTER_KYOGRE},
        .minions = {
            {MONSTER_VAPOREON, MONSTER_VAPOREON},
            {MONSTER_GOREBYSS, MONSTER_HUNTAIL},
        },
        .moves = {
            {MOVE_SELFDESTRUCT, MOVE_NOTHING, MOVE_NOTHING, MOVE_NOTHING},
            {MOVE_SELFDESTRUCT, MOVE_NOTHING, MOVE_NOTHING, MOVE_NOTHING},
        },
        .hasCustomMoves = {TRUE, TRUE},
        .count = 2,
    },
    [TYPE_GRASS] = {
        .species = {MONSTER_CELEBI, MONSTER_VENUSAUR},
        .minions = {
            {MONSTER_TROPIUS, MONSTER_EXEGGUTOR},
            {MONSTER_MEGANIUM, MONSTER_SCEPTILE},
        },
        .moves = {
            {MOVE_SELFDESTRUCT, MOVE_NOTHING, MOVE_NOTHING, MOVE_NOTHING},
            {MOVE_SELFDESTRUCT, MOVE_NOTHING, MOVE_NOTHING, MOVE_NOTHING},
        },
        .hasCustomMoves = {TRUE, TRUE},
        .count = 2,
    },
    [TYPE_ELECTRIC] = {
        .species = {MONSTER_ZAPDOS, MONSTER_RAIKOU},
        .minions = {
            {MONSTER_RAICHU, MONSTER_MANECTRIC},
            {MONSTER_JOLTEON, MONSTER_JOLTEON},
        },
        .moves = {
            {MOVE_SELFDESTRUCT, MOVE_NOTHING, MOVE_NOTHING, MOVE_NOTHING},
            {MOVE_SELFDESTRUCT, MOVE_NOTHING, MOVE_NOTHING, MOVE_NOTHING},
        },
        .hasCustomMoves = {TRUE, TRUE},
        .count = 2,
    },
    [TYPE_ICE] = {
        .species = {MONSTER_ARTICUNO, MONSTER_REGICE},
        .minions = {
            {MONSTER_DEWGONG, MONSTER_CLOYSTER},
            {MONSTER_GLALIE, MONSTER_WALREIN},
        },
        .moves = {
            {MOVE_SELFDESTRUCT, MOVE_NOTHING, MOVE_NOTHING, MOVE_NOTHING},
            {MOVE_SELFDESTRUCT, MOVE_NOTHING, MOVE_NOTHING, MOVE_NOTHING},
        },
        .hasCustomMoves = {TRUE, TRUE},
        .count = 2,
    },
    [TYPE_FIGHTING] = {
        .species = {MONSTER_MACHAMP, MONSTER_MEDICHAM},
        .minions = {
            {MONSTER_HITMONLEE, MONSTER_HITMONCHAN},
            {MONSTER_BRELOOM, MONSTER_HARIYAMA},
        },
        .moves = {
            {MOVE_SELFDESTRUCT, MOVE_NOTHING, MOVE_NOTHING, MOVE_NOTHING},
            {MOVE_SELFDESTRUCT, MOVE_NOTHING, MOVE_NOTHING, MOVE_NOTHING},
        },
        .hasCustomMoves = {TRUE, TRUE},
        .count = 2,
    },
    [TYPE_POISON] = {
        .species = {MONSTER_MUK, MONSTER_CROBAT},
        .minions = {
            {MONSTER_WEEZING, MONSTER_SWALOT},
            {MONSTER_SEVIPER, MONSTER_ARBOK},
        },
        .moves = {
            {MOVE_SELFDESTRUCT, MOVE_NOTHING, MOVE_NOTHING, MOVE_NOTHING},
            {MOVE_SELFDESTRUCT, MOVE_NOTHING, MOVE_NOTHING, MOVE_NOTHING},
        },
        .hasCustomMoves = {TRUE, TRUE},
        .count = 2,
    },
    [TYPE_GROUND] = {
        .species = {MONSTER_GROUDON, MONSTER_CLAYDOL},
        .minions = {
            {MONSTER_RHYDON, MONSTER_ONIX},
            {MONSTER_SOLROCK, MONSTER_LUNATONE},
        },
        .moves = {
            {MOVE_SELFDESTRUCT, MOVE_NOTHING, MOVE_NOTHING, MOVE_NOTHING},
            {MOVE_SELFDESTRUCT, MOVE_NOTHING, MOVE_NOTHING, MOVE_NOTHING},
        },
        .hasCustomMoves = {TRUE, TRUE},
        .count = 2,
    },
    [TYPE_FLYING] = {
        .species = {MONSTER_HO_OH, MONSTER_RAYQUAZA},
        .minions = {
            {MONSTER_SWELLOW, MONSTER_PIDGEOT},
            {MONSTER_AERODACTYL, MONSTER_ALTARIA},
        },
        .moves = {
            {MOVE_SELFDESTRUCT, MOVE_NOTHING, MOVE_NOTHING, MOVE_NOTHING},
            {MOVE_SELFDESTRUCT, MOVE_NOTHING, MOVE_NOTHING, MOVE_NOTHING},
        },
        .hasCustomMoves = {TRUE, TRUE},
        .count = 2,
    },
    [TYPE_PSYCHIC] = {
        .species = {MONSTER_LUGIA, MONSTER_DEOXYS_NORMAL},
        .minions = {
            {MONSTER_XATU, MONSTER_STARMIE},
            {MONSTER_DEOXYS_NORMAL, MONSTER_DEOXYS_NORMAL},
        },
        .moves = {
            {MOVE_SELFDESTRUCT, MOVE_NOTHING, MOVE_NOTHING, MOVE_NOTHING},
            {MOVE_SELFDESTRUCT, MOVE_NOTHING, MOVE_NOTHING, MOVE_NOTHING},
        },
        .hasCustomMoves = {TRUE, TRUE},
        .count = 2,
    },
    [TYPE_BUG] = {
        .species = {MONSTER_HERACROSS, MONSTER_SCIZOR},
        .minions = {
            {MONSTER_BEEDRILL, MONSTER_BUTTERFREE},
            {MONSTER_SCYTHER, MONSTER_SCYTHER},
        },
        .moves = {
            {MOVE_SELFDESTRUCT, MOVE_NOTHING, MOVE_NOTHING, MOVE_NOTHING},
            {MOVE_SELFDESTRUCT, MOVE_NOTHING, MOVE_NOTHING, MOVE_NOTHING},
        },
        .hasCustomMoves = {TRUE, TRUE},
        .count = 2,
    },
    [TYPE_ROCK] = {
        .species = {MONSTER_REGIROCK, MONSTER_TYRANITAR},
        .minions = {
            {MONSTER_CRADILY, MONSTER_ARMALDO},
            {MONSTER_KABUTOPS, MONSTER_OMASTAR},
        },
        .moves = {
            {MOVE_SELFDESTRUCT, MOVE_NOTHING, MOVE_NOTHING, MOVE_NOTHING},
            {MOVE_SELFDESTRUCT, MOVE_NOTHING, MOVE_NOTHING, MOVE_NOTHING},
        },
        .hasCustomMoves = {TRUE, TRUE},
        .count = 2,
    },
    [TYPE_GHOST] = {
        .species = {MONSTER_GENGAR, MONSTER_DUSCLOPS},
        .minions = {
            {MONSTER_BANETTE, MONSTER_SHEDINJA},
            {MONSTER_SABLEYE, MONSTER_MISDREAVUS},
        },
        .moves = {
            {MOVE_SELFDESTRUCT, MOVE_NOTHING, MOVE_NOTHING, MOVE_NOTHING},
            {MOVE_SELFDESTRUCT, MOVE_NOTHING, MOVE_NOTHING, MOVE_NOTHING},
        },
        .hasCustomMoves = {TRUE, TRUE},
        .count = 2,
    },
    [TYPE_DRAGON] = {
        .species = {MONSTER_LATIAS, MONSTER_LATIOS},
        .minions = {
            {MONSTER_DRAGONITE, MONSTER_KINGDRA},
            {MONSTER_SALAMENCE, MONSTER_FLYGON},
        },
        .moves = {
            {MOVE_SELFDESTRUCT, MOVE_NOTHING, MOVE_NOTHING, MOVE_NOTHING},
            {MOVE_SELFDESTRUCT, MOVE_NOTHING, MOVE_NOTHING, MOVE_NOTHING},
        },
        .hasCustomMoves = {TRUE, TRUE},
        .count = 2,
    },
    [TYPE_DARK] = {
        .species = {MONSTER_ABSOL, MONSTER_SHIFTRY},
        .minions = {
            {MONSTER_SABLEYE, MONSTER_MIGHTYENA},
            {MONSTER_CRAWDAUNT, MONSTER_SHARPEDO},
        },
        .moves = {
            {MOVE_SELFDESTRUCT, MOVE_NOTHING, MOVE_NOTHING, MOVE_NOTHING},
            {MOVE_SELFDESTRUCT, MOVE_NOTHING, MOVE_NOTHING, MOVE_NOTHING},
        },
        .hasCustomMoves = {TRUE, TRUE},
        .count = 2,
    },
    [TYPE_STEEL] = {
        .species = {MONSTER_REGISTEEL, MONSTER_JIRACHI},
        .minions = {
            {MONSTER_MAGNETON, MONSTER_SKARMORY},
            {MONSTER_METAGROSS, MONSTER_STEELIX},
        },
        .moves = {
            {MOVE_SELFDESTRUCT, MOVE_NOTHING, MOVE_NOTHING, MOVE_NOTHING},
            {MOVE_SELFDESTRUCT, MOVE_NOTHING, MOVE_NOTHING, MOVE_NOTHING},
        },
        .hasCustomMoves = {TRUE, TRUE},
        .count = 2,
    },
};

const TypeBossWeatherPool gTypeBossWeatherTable[NUM_TYPES] = {
    [TYPE_NONE] = {
        .bosses = {
            {0},
            {0},
        },
        .count = 0,
    },
    [TYPE_NORMAL] = {
        .bosses = {
            { .enabled = FALSE, .weather = WEATHER_CLEAR, .chance = {0, 0, 0} },
            { .enabled = FALSE, .weather = WEATHER_CLEAR, .chance = {0, 0, 0} },
        },
        .count = 2,
    },
    [TYPE_FIRE] = {
        .bosses = {
            { .enabled = TRUE, .weather = WEATHER_SUNNY, .chance = {0, 600, 1000} },
            { .enabled = TRUE, .weather = WEATHER_SUNNY, .chance = {0, 600, 1000} },
        },
        .count = 2,
    },
    [TYPE_WATER] = {
        .bosses = {
            { .enabled = TRUE, .weather = WEATHER_FOG, .chance = {0, 600, 1000} },
            { .enabled = FALSE, .weather = WEATHER_CLEAR, .chance = {0, 0, 0} },
        },
        .count = 2,
    },
    [TYPE_GRASS] = {
        .bosses = {
            { .enabled = FALSE, .weather = WEATHER_CLEAR, .chance = {0, 0, 0} },
            { .enabled = TRUE, .weather = WEATHER_SUNNY, .chance = {0, 600, 1000} },
        },
        .count = 2,
    },
    [TYPE_ELECTRIC] = {
        .bosses = {
            { .enabled = FALSE, .weather = WEATHER_CLEAR, .chance = {0, 0, 0} },
            { .enabled = FALSE, .weather = WEATHER_CLEAR, .chance = {0, 0, 0} },
        },
        .count = 2,
    },
    [TYPE_ICE] = {
        .bosses = {
            { .enabled = TRUE, .weather = WEATHER_SNOW, .chance = {0, 600, 1000} },
            { .enabled = TRUE, .weather = WEATHER_HAIL, .chance = {0, 600, 1000} },
        },
        .count = 2,
    },
    [TYPE_FIGHTING] = {
        .bosses = {
            { .enabled = FALSE, .weather = WEATHER_CLEAR, .chance = {0, 0, 0} },
            { .enabled = FALSE, .weather = WEATHER_CLEAR, .chance = {0, 0, 0} },
        },
        .count = 2,
    },
    [TYPE_POISON] = {
        .bosses = {
            { .enabled = FALSE, .weather = WEATHER_CLEAR, .chance = {0, 0, 0} },
            { .enabled = FALSE, .weather = WEATHER_CLEAR, .chance = {0, 0, 0} },
        },
        .count = 2,
    },
    [TYPE_GROUND] = {
        .bosses = {
            { .enabled = FALSE, .weather = WEATHER_CLEAR, .chance = {0, 0, 0} },
            { .enabled = FALSE, .weather = WEATHER_CLEAR, .chance = {0, 0, 0} },
        },
        .count = 2,
    },
    [TYPE_FLYING] = {
        .bosses = {
            { .enabled = FALSE, .weather = WEATHER_CLEAR, .chance = {0, 0, 0} },
            { .enabled = FALSE, .weather = WEATHER_CLEAR, .chance = {0, 0, 0} },
        },
        .count = 2,
    },
    [TYPE_PSYCHIC] = {
        .bosses = {
            { .enabled = TRUE, .weather = WEATHER_FOG, .chance = {0, 600, 1000} },
            { .enabled = FALSE, .weather = WEATHER_CLEAR, .chance = {0, 0, 0} },
        },
        .count = 2,
    },
    [TYPE_BUG] = {
        .bosses = {
            { .enabled = FALSE, .weather = WEATHER_CLEAR, .chance = {0, 0, 0} },
            { .enabled = FALSE, .weather = WEATHER_CLEAR, .chance = {0, 0, 0} },
        },
        .count = 2,
    },
    [TYPE_ROCK] = {
        .bosses = {
            { .enabled = TRUE, .weather = WEATHER_SANDSTORM, .chance = {0, 600, 1000} },
            { .enabled = FALSE, .weather = WEATHER_CLEAR, .chance = {0, 0, 0} },
        },
        .count = 2,
    },
    [TYPE_GHOST] = {
        .bosses = {
            { .enabled = FALSE, .weather = WEATHER_CLEAR, .chance = {0, 0, 0} },
            { .enabled = FALSE, .weather = WEATHER_CLEAR, .chance = {0, 0, 0} },
        },
        .count = 2,
    },
    [TYPE_DRAGON] = {
        .bosses = {
            { .enabled = FALSE, .weather = WEATHER_CLEAR, .chance = {0, 0, 0} },
            { .enabled = FALSE, .weather = WEATHER_CLEAR, .chance = {0, 0, 0} },
        },
        .count = 2,
    },
    [TYPE_DARK] = {
        .bosses = {
            { .enabled = FALSE, .weather = WEATHER_CLEAR, .chance = {0, 0, 0} },
            { .enabled = FALSE, .weather = WEATHER_CLEAR, .chance = {0, 0, 0} },
        },
        .count = 2,
    },
    [TYPE_STEEL] = {
        .bosses = {
            { .enabled = FALSE, .weather = WEATHER_CLEAR, .chance = {0, 0, 0} },
            { .enabled = FALSE, .weather = WEATHER_CLEAR, .chance = {0, 0, 0} },
        },
        .count = 2,
    },
};
